"""Initial baseline

Revision ID: eee548a5f521
Revises: None
Create Date: 2026-08-04 13:05:12.394957

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eee548a5f521"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ctms_audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("user_role", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("details", sa.String(length=1000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_audit_logs_timestamp"),
        "ctms_audit_logs",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctms_audit_logs_user_id"), "ctms_audit_logs", ["user_id"], unique=False
    )
    op.create_table(
        "ctms_clinical_queries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=255), nullable=False),
        sa.Column("site_id", sa.String(length=255), nullable=False),
        sa.Column("visit_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("explanation", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_clinical_queries_site_id"),
        "ctms_clinical_queries",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctms_clinical_queries_study_id"),
        "ctms_clinical_queries",
        ["study_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctms_clinical_queries_visit_id"),
        "ctms_clinical_queries",
        ["visit_id"],
        unique=False,
    )
    op.create_table(
        "ctms_cra_allocations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cra_id", sa.String(length=255), nullable=False),
        sa.Column("site_id", sa.String(length=255), nullable=False),
        sa.Column("study_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("effective_start_date", sa.DateTime(), nullable=False),
        sa.Column("effective_end_date", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_cra_allocations_cra_id"),
        "ctms_cra_allocations",
        ["cra_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctms_cra_allocations_site_id"),
        "ctms_cra_allocations",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctms_cra_allocations_study_id"),
        "ctms_cra_allocations",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "ctms_defeated_monitoring_visits",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("visit_id", sa.String(length=255), nullable=False),
        sa.Column("actual_date", sa.DateTime(), nullable=True),
        sa.Column("findings", sa.JSON(), nullable=True),
        sa.Column("device_timestamp", sa.DateTime(), nullable=False),
        sa.Column("offline_sync_markers", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("reason_for_change", sa.String(length=500), nullable=True),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_defeated_monitoring_visits_visit_id"),
        "ctms_defeated_monitoring_visits",
        ["visit_id"],
        unique=False,
    )
    op.create_table(
        "ctms_delegations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("site_id", sa.String(length=255), nullable=False),
        sa.Column("staff_user_id", sa.String(length=255), nullable=False),
        sa.Column("task_codes", sa.JSON(), nullable=False),
        sa.Column("start_date", sa.String(length=50), nullable=False),
        sa.Column("end_date", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("signed_off", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_delegations_site_id"),
        "ctms_delegations",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctms_delegations_staff_user_id"),
        "ctms_delegations",
        ["staff_user_id"],
        unique=False,
    )
    op.create_table(
        "ctms_generated_letters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("visit_id", sa.String(length=36), nullable=False),
        sa.Column("letter_type", sa.String(length=50), nullable=False),
        sa.Column("rendered_content", sa.String(length=100000), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_generated_letters_visit_id"),
        "ctms_generated_letters",
        ["visit_id"],
        unique=False,
    )
    op.create_table(
        "ctms_investigator_grants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=255), nullable=False),
        sa.Column("site_id", sa.String(length=255), nullable=False),
        sa.Column("total_budget", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_investigator_grants_site_id"),
        "ctms_investigator_grants",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctms_investigator_grants_study_id"),
        "ctms_investigator_grants",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "ctms_monitoring_visit_findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("visit_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.String(length=1000), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("resolution_status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.Column("offline_sync_markers", sa.JSON(), nullable=True),
        sa.Column("sync_status", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_monitoring_visit_findings_visit_id"),
        "ctms_monitoring_visit_findings",
        ["visit_id"],
        unique=False,
    )
    op.create_table(
        "ctms_monitoring_visits",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=255), nullable=False),
        sa.Column("site_id", sa.String(length=255), nullable=False),
        sa.Column("cra_id", sa.String(length=255), nullable=False),
        sa.Column("visit_type", sa.String(length=50), nullable=False),
        sa.Column("scheduled_date", sa.DateTime(), nullable=False),
        sa.Column("actual_date", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.Column("signature_manifestation", sa.JSON(), nullable=True),
        sa.Column("signer", sa.String(length=255), nullable=True),
        sa.Column("signing_timestamp", sa.DateTime(), nullable=True),
        sa.Column("offline_sync_markers", sa.JSON(), nullable=True),
        sa.Column("sync_status", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_monitoring_visits_site_id"),
        "ctms_monitoring_visits",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctms_monitoring_visits_study_id"),
        "ctms_monitoring_visits",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "ctms_recruitment_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("site_id", sa.String(length=255), nullable=False),
        sa.Column("study_id", sa.String(length=255), nullable=False),
        sa.Column("screened_count", sa.Integer(), nullable=False),
        sa.Column("enrolled_count", sa.Integer(), nullable=False),
        sa.Column("target_count", sa.Integer(), nullable=False),
        sa.Column("as_of_date", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_recruitment_records_site_id"),
        "ctms_recruitment_records",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctms_recruitment_records_study_id"),
        "ctms_recruitment_records",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "ctms_regulatory_forms",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=255), nullable=False),
        sa.Column("site_id", sa.String(length=255), nullable=True),
        sa.Column("form_type", sa.String(length=50), nullable=False),
        sa.Column("rendered_content", sa.String(length=100000), nullable=False),
        sa.Column("approval_status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.Column("signature_manifestation", sa.JSON(), nullable=True),
        sa.Column("signer", sa.String(length=255), nullable=True),
        sa.Column("signing_timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_regulatory_forms_site_id"),
        "ctms_regulatory_forms",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctms_regulatory_forms_study_id"),
        "ctms_regulatory_forms",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "ctms_site_milestones",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("site_id", sa.String(length=255), nullable=False),
        sa.Column("study_id", sa.String(length=255), nullable=False),
        sa.Column("milestone_type", sa.String(length=100), nullable=False),
        sa.Column("planned_date", sa.DateTime(), nullable=True),
        sa.Column("actual_date", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_site_milestones_milestone_type"),
        "ctms_site_milestones",
        ["milestone_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctms_site_milestones_site_id"),
        "ctms_site_milestones",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctms_site_milestones_study_id"),
        "ctms_site_milestones",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "ctms_studies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_studies_study_id"), "ctms_studies", ["study_id"], unique=False
    )
    op.create_table(
        "site_staff_members",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("site_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("primary_role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("license_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("gcp_certified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "reason_for_change", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_site_staff_members_site_id"),
        "site_staff_members",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_site_staff_members_user_id"),
        "site_staff_members",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "ctms_budget_line_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("grant_id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grant_id"], ["ctms_investigator_grants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_budget_line_items_grant_id"),
        "ctms_budget_line_items",
        ["grant_id"],
        unique=False,
    )
    op.create_table(
        "ctms_payment_milestones",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("grant_id", sa.String(length=36), nullable=False),
        sa.Column("milestone_name", sa.String(length=255), nullable=False),
        sa.Column("trigger_condition", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("is_triggered", sa.Boolean(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grant_id"], ["ctms_investigator_grants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_payment_milestones_grant_id"),
        "ctms_payment_milestones",
        ["grant_id"],
        unique=False,
    )
    op.create_table(
        "doa_delegation_records",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("site_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("staff_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "pi_signature_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("pi_approved_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "reason_for_change", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["staff_user_id"],
            ["site_staff_members.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_doa_delegation_records_site_id"),
        "doa_delegation_records",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_doa_delegation_records_staff_user_id"),
        "doa_delegation_records",
        ["staff_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_doa_delegation_records_task_code"),
        "doa_delegation_records",
        ["task_code"],
        unique=False,
    )
    op.create_table(
        "ctms_investigator_payables",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("grant_id", sa.String(length=36), nullable=False),
        sa.Column("milestone_id", sa.String(length=36), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("payment_status", sa.String(length=50), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grant_id"], ["ctms_investigator_grants.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["milestone_id"], ["ctms_payment_milestones.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_investigator_payables_grant_id"),
        "ctms_investigator_payables",
        ["grant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctms_investigator_payables_milestone_id"),
        "ctms_investigator_payables",
        ["milestone_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ctms_investigator_payables_milestone_id"),
        table_name="ctms_investigator_payables",
    )
    op.drop_index(
        op.f("ix_ctms_investigator_payables_grant_id"),
        table_name="ctms_investigator_payables",
    )
    op.drop_table("ctms_investigator_payables")
    op.drop_index(
        op.f("ix_doa_delegation_records_task_code"), table_name="doa_delegation_records"
    )
    op.drop_index(
        op.f("ix_doa_delegation_records_staff_user_id"),
        table_name="doa_delegation_records",
    )
    op.drop_index(
        op.f("ix_doa_delegation_records_site_id"), table_name="doa_delegation_records"
    )
    op.drop_table("doa_delegation_records")
    op.drop_index(
        op.f("ix_ctms_payment_milestones_grant_id"),
        table_name="ctms_payment_milestones",
    )
    op.drop_table("ctms_payment_milestones")
    op.drop_index(
        op.f("ix_ctms_budget_line_items_grant_id"), table_name="ctms_budget_line_items"
    )
    op.drop_table("ctms_budget_line_items")
    op.drop_index(
        op.f("ix_site_staff_members_user_id"), table_name="site_staff_members"
    )
    op.drop_index(
        op.f("ix_site_staff_members_site_id"), table_name="site_staff_members"
    )
    op.drop_table("site_staff_members")
    op.drop_index(op.f("ix_ctms_studies_study_id"), table_name="ctms_studies")
    op.drop_table("ctms_studies")
    op.drop_index(
        op.f("ix_ctms_site_milestones_study_id"), table_name="ctms_site_milestones"
    )
    op.drop_index(
        op.f("ix_ctms_site_milestones_site_id"), table_name="ctms_site_milestones"
    )
    op.drop_index(
        op.f("ix_ctms_site_milestones_milestone_type"),
        table_name="ctms_site_milestones",
    )
    op.drop_table("ctms_site_milestones")
    op.drop_index(
        op.f("ix_ctms_regulatory_forms_study_id"), table_name="ctms_regulatory_forms"
    )
    op.drop_index(
        op.f("ix_ctms_regulatory_forms_site_id"), table_name="ctms_regulatory_forms"
    )
    op.drop_table("ctms_regulatory_forms")
    op.drop_index(
        op.f("ix_ctms_recruitment_records_study_id"),
        table_name="ctms_recruitment_records",
    )
    op.drop_index(
        op.f("ix_ctms_recruitment_records_site_id"),
        table_name="ctms_recruitment_records",
    )
    op.drop_table("ctms_recruitment_records")
    op.drop_index(
        op.f("ix_ctms_monitoring_visits_study_id"), table_name="ctms_monitoring_visits"
    )
    op.drop_index(
        op.f("ix_ctms_monitoring_visits_site_id"), table_name="ctms_monitoring_visits"
    )
    op.drop_table("ctms_monitoring_visits")
    op.drop_index(
        op.f("ix_ctms_monitoring_visit_findings_visit_id"),
        table_name="ctms_monitoring_visit_findings",
    )
    op.drop_table("ctms_monitoring_visit_findings")
    op.drop_index(
        op.f("ix_ctms_investigator_grants_study_id"),
        table_name="ctms_investigator_grants",
    )
    op.drop_index(
        op.f("ix_ctms_investigator_grants_site_id"),
        table_name="ctms_investigator_grants",
    )
    op.drop_table("ctms_investigator_grants")
    op.drop_index(
        op.f("ix_ctms_generated_letters_visit_id"), table_name="ctms_generated_letters"
    )
    op.drop_table("ctms_generated_letters")
    op.drop_index(
        op.f("ix_ctms_delegations_staff_user_id"), table_name="ctms_delegations"
    )
    op.drop_index(op.f("ix_ctms_delegations_site_id"), table_name="ctms_delegations")
    op.drop_table("ctms_delegations")
    op.drop_index(
        op.f("ix_ctms_defeated_monitoring_visits_visit_id"),
        table_name="ctms_defeated_monitoring_visits",
    )
    op.drop_table("ctms_defeated_monitoring_visits")
    op.drop_index(
        op.f("ix_ctms_cra_allocations_study_id"), table_name="ctms_cra_allocations"
    )
    op.drop_index(
        op.f("ix_ctms_cra_allocations_site_id"), table_name="ctms_cra_allocations"
    )
    op.drop_index(
        op.f("ix_ctms_cra_allocations_cra_id"), table_name="ctms_cra_allocations"
    )
    op.drop_table("ctms_cra_allocations")
    op.drop_index(
        op.f("ix_ctms_clinical_queries_visit_id"), table_name="ctms_clinical_queries"
    )
    op.drop_index(
        op.f("ix_ctms_clinical_queries_study_id"), table_name="ctms_clinical_queries"
    )
    op.drop_index(
        op.f("ix_ctms_clinical_queries_site_id"), table_name="ctms_clinical_queries"
    )
    op.drop_table("ctms_clinical_queries")
    op.drop_index(op.f("ix_ctms_audit_logs_user_id"), table_name="ctms_audit_logs")
    op.drop_index(op.f("ix_ctms_audit_logs_timestamp"), table_name="ctms_audit_logs")
    op.drop_table("ctms_audit_logs")
    # ### end Alembic commands ###
