"""
Standard Part 11 compliant audit and metadata fields for Pydantic v2.
"""

from datetime import datetime, timezone
from enum import Enum

from datetime_helpers import AwareDatetime
from pydantic import BaseModel, Field, field_validator


class AuditAction(str, Enum):
    """
    Controlled actions for 21 CFR Part 11 compliant audit trail logging.

    Provides a standardized taxonomy for tracking and auditing changes
    to digital records and signatures across all eClinical microservices.
    """

    # Generic CRUD/read
    CREATE = "CREATE"
    READ = "READ"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    VIEW = "VIEW"
    LIST = "LIST"

    # Document lifecycle
    INGEST = "INGEST"
    DOWNLOAD = "DOWNLOAD"
    WATERMARKED_DOWNLOAD = "WATERMARKED_DOWNLOAD"
    REDACT = "REDACT"
    SIGN = "SIGN"
    APPROVE = "APPROVE"
    QC_TRANSITION = "QC_TRANSITION"
    BINDER_EXPORT = "BINDER_EXPORT"
    COMPLETENESS = "COMPLETENESS"
    MUTATION_REJECTED = "MUTATION_REJECTED"
    AUDIT_VIEW = "AUDIT_VIEW"
    EDL_VIEW = "EDL_VIEW"
    EDL_UPDATE = "EDL_UPDATE"
    QC_HISTORY_VIEW = "QC_HISTORY_VIEW"

    # Approval/sign-off
    SIGN_OFF = "SIGN_OFF"
    SIGN_OFF_VISIT = "SIGN_OFF_VISIT"

    # Security
    SECURITY_ALERT = "SECURITY_ALERT"

    # eISF Domain / Document Verbs
    SYNC = "SYNC"
    CREATE_DOCUMENT = "CREATE_DOCUMENT"
    UPDATE_DOCUMENT = "UPDATE_DOCUMENT"
    DELETE_DOCUMENT = "DELETE_DOCUMENT"
    VIEW_DOCUMENT = "VIEW_DOCUMENT"
    INGEST_NOOP = "INGEST_NOOP"
    DEDUPLICATED = "DEDUPLICATED"

    # eConsent Translation and Archival Actions
    CREATE_TRANSLATION = "CREATE_TRANSLATION"
    UPDATE_TRANSLATION = "UPDATE_TRANSLATION"
    LIST_TRANSLATIONS = "LIST_TRANSLATIONS"
    VIEW_TRANSLATION = "VIEW_TRANSLATION"
    TRANSITION_TRANSLATION = "TRANSITION_TRANSLATION"
    VIEW_APPROVED_TRANSLATION = "VIEW_APPROVED_TRANSLATION"
    CAPTURE_CONSENT = "CAPTURE_CONSENT"
    DEFINE_COMPREHENSION_CHECK = "DEFINE_COMPREHENSION_CHECK"
    COMPREHENSION_EVALUATION = "COMPREHENSION_EVALUATION"
    SIGN_CONSENT = "SIGN_CONSENT"
    ARCHIVAL_QUEUED = "ARCHIVAL_QUEUED"
    ARCHIVAL_ACCEPTED = "ARCHIVAL_ACCEPTED"
    ARCHIVAL_FAILED = "ARCHIVAL_FAILED"

    # CTMS Visit/Grant/Milestone/Allocation Verbs
    TRIGGER_MILESTONE = "TRIGGER_MILESTONE"
    CREATE_STUDY = "CREATE_STUDY"
    LIST_STUDIES = "LIST_STUDIES"
    VIEW_AUDIT_LOGS = "VIEW_AUDIT_LOGS"
    CREATE_VISIT = "CREATE_VISIT"
    GENERATE_LETTER = "GENERATE_LETTER"
    COMPLETE_VISIT = "COMPLETE_VISIT"
    CREATE_FINDING = "CREATE_FINDING"
    LIST_VISITS = "LIST_VISITS"
    RETRIEVE_LETTERS = "RETRIEVE_LETTERS"
    RETRIEVE_LETTER = "RETRIEVE_LETTER"
    CREATE_RECRUITMENT_RECORD = "CREATE_RECRUITMENT_RECORD"
    LIST_RECRUITMENT_RECORDS = "LIST_RECRUITMENT_RECORDS"
    CREATE_MILESTONE = "CREATE_MILESTONE"
    UPDATE_MILESTONE = "UPDATE_MILESTONE"
    LIST_SITE_MILESTONES = "LIST_SITE_MILESTONES"
    DEACTIVATE_CRA_ALLOCATION = "DEACTIVATE_CRA_ALLOCATION"
    CREATE_CRA_ALLOCATION = "CREATE_CRA_ALLOCATION"
    UPDATE_CRA_ALLOCATION = "UPDATE_CRA_ALLOCATION"
    LIST_CRA_ALLOCATIONS = "LIST_CRA_ALLOCATIONS"
    VIEW_WORKLOAD_SUMMARY = "VIEW_WORKLOAD_SUMMARY"
    CREATE_GRANT = "CREATE_GRANT"
    LIST_GRANTS = "LIST_GRANTS"
    GET_GRANT = "GET_GRANT"
    UPDATE_GRANT = "UPDATE_GRANT"
    CREATE_BUDGET_ITEM = "CREATE_BUDGET_ITEM"
    LIST_BUDGET_ITEMS = "LIST_BUDGET_ITEMS"
    CREATE_PAYMENT_MILESTONE = "CREATE_PAYMENT_MILESTONE"
    LIST_PAYMENT_MILESTONES = "LIST_PAYMENT_MILESTONES"
    MANUAL_TRIGGER_MILESTONE = "MANUAL_TRIGGER_MILESTONE"
    EVALUATE_MILESTONES = "EVALUATE_MILESTONES"
    LIST_PAYABLES = "LIST_PAYABLES"
    MONITORING_VISIT_STRUCTURAL_CONFLICT = "MONITORING_VISIT_STRUCTURAL_CONFLICT"
    MONITORING_VISIT_RECONCILE = "MONITORING_VISIT_RECONCILE"
    DELEGATE_TASK = "DELEGATE_TASK"
    APPROVE_DELEGATION = "APPROVE_DELEGATION"
    REVOKE_DELEGATION = "REVOKE_DELEGATION"
    DOA_LOG_MODIFIED = "DOA_LOG_MODIFIED"

    # Quality Deviation / CAPA Verbs
    CAPA_CREATE = "CAPA_CREATE"
    CAPA_TRANSITION = "CAPA_TRANSITION"
    CAPA_UPDATE = "CAPA_UPDATE"
    DEVIATION_CREATE = "DEVIATION_CREATE"
    DEVIATION_LIST = "DEVIATION_LIST"
    DEVIATION_UPDATE = "DEVIATION_UPDATE"
    DEVIATION_VIEW = "DEVIATION_VIEW"
    RCA_CREATE = "RCA_CREATE"
    RCA_UPDATE = "RCA_UPDATE"

    # Safety Reconciliation and Case Actions
    RECONCILIATION_ALERT_FAILED = "RECONCILIATION_ALERT_FAILED"
    RECONCILIATION_ALERT_SENT = "RECONCILIATION_ALERT_SENT"
    RECONCILIATION_JOB_COMPLETED = "RECONCILIATION_JOB_COMPLETED"
    RECONCILIATION_JOB_CREATE = "RECONCILIATION_JOB_CREATE"
    RECONCILIATION_JOB_FAILED = "RECONCILIATION_JOB_FAILED"
    RECONCILIATION_JOB_LIST = "RECONCILIATION_JOB_LIST"
    RECONCILIATION_JOB_PROCESSING = "RECONCILIATION_JOB_PROCESSING"
    RECONCILIATION_JOB_VIEW = "RECONCILIATION_JOB_VIEW"
    SAE_RECONCILIATION_RUN = "SAE_RECONCILIATION_RUN"
    SAE_RECONCILIATION_RUN_LIST = "SAE_RECONCILIATION_RUN_LIST"
    SAE_RECONCILIATION_RUN_VIEW = "SAE_RECONCILIATION_RUN_VIEW"
    SAFETY_AUDIT_LOG_LIST = "SAFETY_AUDIT_LOG_LIST"
    SAFETY_CASE_CREATE = "SAFETY_CASE_CREATE"
    SAFETY_CASE_LIST = "SAFETY_CASE_LIST"
    SAFETY_CASE_VIEW = "SAFETY_CASE_VIEW"
    SAFETY_EXPORT_JOB_CREATE = "SAFETY_EXPORT_JOB_CREATE"
    SAFETY_EXPORT_JOB_LIST = "SAFETY_EXPORT_JOB_LIST"
    SAFETY_EXPORT_JOB_VIEW = "SAFETY_EXPORT_JOB_VIEW"

    # Organization and Personnel Administration Actions
    DELEGATION_GRANT = "DELEGATION_GRANT"
    DELEGATION_HISTORY = "DELEGATION_HISTORY"
    DELEGATION_LIST = "DELEGATION_LIST"
    DELEGATION_REVOKE = "DELEGATION_REVOKE"
    DELEGATION_SIGN = "DELEGATION_SIGN"
    DELEGATION_VIEW = "DELEGATION_VIEW"
    ORGANIZATION_CREATE = "ORGANIZATION_CREATE"
    ORGANIZATION_HISTORY = "ORGANIZATION_HISTORY"
    ORGANIZATION_LIST = "ORGANIZATION_LIST"
    ORGANIZATION_UPDATE = "ORGANIZATION_UPDATE"
    ORGANIZATION_VIEW = "ORGANIZATION_VIEW"
    PERSONNEL_ASSIGNMENT_CREATE = "PERSONNEL_ASSIGNMENT_CREATE"
    PERSONNEL_ASSIGNMENT_HISTORY = "PERSONNEL_ASSIGNMENT_HISTORY"
    PERSONNEL_ASSIGNMENT_LIST = "PERSONNEL_ASSIGNMENT_LIST"
    PERSONNEL_ASSIGNMENT_RESOLVE = "PERSONNEL_ASSIGNMENT_RESOLVE"
    PERSONNEL_ASSIGNMENT_UPDATE = "PERSONNEL_ASSIGNMENT_UPDATE"
    PERSONNEL_CREATE = "PERSONNEL_CREATE"
    PERSONNEL_HISTORY = "PERSONNEL_HISTORY"
    PERSONNEL_LIST = "PERSONNEL_LIST"
    PERSONNEL_UPDATE = "PERSONNEL_UPDATE"
    PERSONNEL_VIEW = "PERSONNEL_VIEW"
    SITE_CREATE = "SITE_CREATE"
    SITE_HISTORY = "SITE_HISTORY"
    SITE_LIST = "SITE_LIST"
    SITE_UPDATE = "SITE_UPDATE"
    SITE_VIEW = "SITE_VIEW"

    # Interoperability (eCOA / ePRO) Actions
    EPRO_BULK_SYNC = "EPRO_BULK_SYNC"
    EPRO_RECONCILE = "EPRO_RECONCILE"
    EPRO_STRUCTURAL_CONFLICT = "EPRO_STRUCTURAL_CONFLICT"
    EPRO_SUBMIT = "EPRO_SUBMIT"
    FHIR_PREFILL = "FHIR_PREFILL"
    FHIR_PRESCREEN = "FHIR_PRESCREEN"
    CREATE_INSTRUMENT = "CREATE_INSTRUMENT"
    CREATE_ASSIGNMENT = "CREATE_ASSIGNMENT"
    COMPUTE_REMINDERS = "COMPUTE_REMINDERS"
    ACKNOWLEDGE_NOTIFICATION = "ACKNOWLEDGE_NOTIFICATION"

    # Notifications Service Actions
    NOTIFICATION_ACKNOWLEDGE = "NOTIFICATION_ACKNOWLEDGE"
    NOTIFICATION_CREATE = "NOTIFICATION_CREATE"
    NOTIFICATION_DELIVERY_EXHAUSTED = "NOTIFICATION_DELIVERY_EXHAUSTED"
    NOTIFICATION_DELIVERY_FAILED = "NOTIFICATION_DELIVERY_FAILED"
    NOTIFICATION_LIST = "NOTIFICATION_LIST"
    NOTIFICATION_RESOLVE = "NOTIFICATION_RESOLVE"
    NOTIFICATION_VIEW = "NOTIFICATION_VIEW"

    # Tickets and Issue Tracking Actions
    TICKET_ASSIGN = "TICKET_ASSIGN"
    TICKET_AUDIT_LOG_LIST = "TICKET_AUDIT_LOG_LIST"
    TICKET_COMMENTS_VIEW = "TICKET_COMMENTS_VIEW"
    TICKET_COMMENT_CREATE = "TICKET_COMMENT_CREATE"
    TICKET_CREATE = "TICKET_CREATE"
    TICKET_LIST = "TICKET_LIST"
    TICKET_TRANSITION = "TICKET_TRANSITION"
    TICKET_UPDATE = "TICKET_UPDATE"
    TICKET_VIEW = "TICKET_VIEW"

    # Clinical Trial Execution & Other Operations
    EMERGENCY_UNBLINDING = "EMERGENCY_UNBLINDING"
    CONFLICT = "CONFLICT"
    OFFLINE_SYNC_BATCH = "OFFLINE_SYNC_BATCH"
    DOCUMENT_VIEW = "DOCUMENT_VIEW"
    BINDER_STRUCTURE_VIEW = "BINDER_STRUCTURE_VIEW"
    STUDY_ARCHIVE = "STUDY_ARCHIVE"
    EXPIRATION_ALERT_DISPATCH = "EXPIRATION_ALERT_DISPATCH"
    EXPIRATION_ALERT_DISPATCH_FAILED = "EXPIRATION_ALERT_DISPATCH_FAILED"
    EMAIL_INGEST = "EMAIL_INGEST"
    MEDICAL_MONITOR_ALERT_ATTEMPT = "MEDICAL_MONITOR_ALERT_ATTEMPT"
    AUDIT_LOG_LIST = "AUDIT_LOG_LIST"


class AuditFields(BaseModel):
    """
    A reusable Pydantic v2 model/mixin containing standard 21 CFR Part 11
    compliant audit and metadata fields.
    """

    created_at: AwareDatetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Chronological UTC timestamp when the record was created.",
    )
    created_by: str = Field(
        ...,
        description="Unique identifier (e.g. username/OIDC user_id) of the user who created the record.",
    )
    reason_for_change: str = Field(
        ...,
        description="Mandatory explanation or audit justification for creating or mutating this record.",
    )
    version_index: int = Field(
        default=1,
        description="Optimistic locking or row version counter, initialized to 1.",
    )

    @field_validator("reason_for_change")
    @classmethod
    def validate_reason_for_change(cls, v: str) -> str:
        """
        Validate that the reason_for_change is a non-empty, non-blank string.
        """
        if not isinstance(v, str) or not v.strip():
            raise ValueError(
                "Reason for change cannot be empty or consist only of whitespace."
            )
        return v
