import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));

const MODEL_PATH = path.resolve(
  __dirname,
  "../../../docs/CDISC/Library/Data_Collection/CDASH_Model_v1.3.json"
);
const IG_PATH = path.resolve(
  __dirname,
  "../../../docs/CDISC/Library/Data_Collection/CDASHIG_v2.3.json"
);
const OUTPUT_DIR = path.resolve(__dirname, "../src/types");
const OUTPUT_FILE = path.resolve(OUTPUT_DIR, "cdash.ts");

function sanitizeJson(filePath) {
  const raw = fs.readFileSync(filePath, "utf8");
  const sanitized = raw.replace(/:\s*NaN\b/g, ": null");
  return JSON.parse(sanitized);
}

function generate() {
  console.log("Generating CDASH TypeScript definitions...");

  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  const modelData = sanitizeJson(MODEL_PATH);
  const igData = sanitizeJson(IG_PATH);

  const modelVars = modelData.Variables || [];
  const igVars = igData.Variables || [];

  // Collect unique variable codes
  const variableCodesSet = new Set();
  modelVars.forEach((v) => {
    if (v["CDASH Variable"]) {
      variableCodesSet.add(v["CDASH Variable"]);
    }
  });
  igVars.forEach((v) => {
    if (v["CDASHIG Variable"]) {
      variableCodesSet.add(v["CDASHIG Variable"]);
    }
  });

  const variableCodes = Array.from(variableCodesSet).sort();

  // Create typescript code
  const tsCode = `// Auto-generated CDASH and CDASHIG TypeScript interfaces
// Generated directly from CDISC CDASH v1.3 and CDASHIG v2.3 schemas.
// DO NOT EDIT THIS FILE MANUALLY.

/**
 * Represents a variable definition in the CDASH Model v1.3
 */
export interface CDASHModelVariable {
  "Version": string;
  "Class": string;
  "Domain": string | null;
  "Variable Order": number | null;
  "CDASH Variable": string;
  "CDASH Variable Label": string;
  "DRAFT CDASH Definition"?: string | null;
  "Domain Specific"?: boolean | null;
  "Question Text"?: string | null;
  "Prompt"?: string | null;
  "Type": string;
  "SDTM Target"?: string | null;
  "Mapping Instructions"?: string | null;
  "Controlled Terminology Codelist Code"?: string | null;
  "Implementation Notes"?: string | null;
}

/**
 * Represents a variable definition in the CDASHIG v2.3
 */
export interface CDASHIGVariable {
  "Version": string;
  "Class": string;
  "Domain": string;
  "Data Collection Scenario/Implementation Option"?: string | null;
  "Variable Order": number | null;
  "CDASHIG Variable": string;
  "CDASHIG Variable Label": string;
  "DRAFT CDASHIG Definition"?: string | null;
  "Question Text"?: string | null;
  "Prompt"?: string | null;
  "Type": string;
  "CDASHIG Core": "HR" | "R" | "O" | string;
  "Case Report Form Completion Instructions"?: string | null;
  "SDTMIG Target"?: string | null;
  "Mapping Instructions"?: string | null;
  "CDISC CT Codelist Code(s), Subset Codes(s)"?: string | null;
  "CDISC CT Codelist Submission Values(s), Subset Submission Value(s)"?: string | null;
  "Implementation Notes"?: string | null;
}

/**
 * A union type of all valid variable names from both CDASH Model v1.3 and CDASHIG v2.3 schemas
 */
export type CdashVariableCode =
${variableCodes.map((code) => `  | ${JSON.stringify(code)}`).join("\n")};

/**
 * Strict interface definition for clinical fields used by form components.
 * Restricts input to valid CDASH field properties.
 */
export interface CdashField {
  id: string;
  label: string;
  type: "radio" | "choice_single" | "concept_code" | "text" | string;
  cdash?: CdashVariableCode | null;
  gridSpan?: number | string;
  options?: any[] | null;
  required?: boolean;
  [key: string]: any;
}
`;

  fs.writeFileSync(OUTPUT_FILE, tsCode, "utf8");
  console.log("Successfully generated " + OUTPUT_FILE);
}

generate();
