from enum import StrEnum


class DeviationStatus(StrEnum):
    REPORTED = "REPORTED"
    UNDER_INVESTIGATION = "UNDER_INVESTIGATION"
    RCA_COMPLETE = "RCA_COMPLETE"
    CAPA_INITIATED = "CAPA_INITIATED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class CAPAStatus(StrEnum):
    INITIATED = "INITIATED"
    UNDER_REVIEW = "UNDER_REVIEW"
    IMPLEMENTATION = "IMPLEMENTATION"
    EFFECTIVENESS_CHECK = "EFFECTIVENESS_CHECK"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class DeviationSeverity(StrEnum):
    MINOR = "MINOR"
    MAJOR = "MAJOR"
    CRITICAL = "CRITICAL"


class DeviationType(StrEnum):
    INFORMED_CONSENT = "INFORMED_CONSENT"
    ELIGIBILITY = "ELIGIBILITY"
    PROTOCOL_PROCEDURE = "PROTOCOL_PROCEDURE"
    SAFETY_REPORTING = "SAFETY_REPORTING"
    INVESTIGATIONAL_PRODUCT = "INVESTIGATIONAL_PRODUCT"
    OTHER = "OTHER"
