from enum import StrEnum


class DeviationStatus(StrEnum):
    REPORTED = "REPORTED"
    UNDER_INVESTIGATION = "UNDER_INVESTIGATION"
    RCA_COMPLETE = "RCA_COMPLETE"
    CAPA_INITIATED = "CAPA_INITIATED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class CAPAStatus(StrEnum):
    INITIATED = "INITIATED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    IMPLEMENTATION = "IMPLEMENTATION"
    IMPLEMENTATION_VERIFIED = "IMPLEMENTATION_VERIFIED"
    EFFECTIVENESS_CHECK = "EFFECTIVENESS_CHECK"
    CLOSED = "CLOSED"
    INEFFECTIVE = "INEFFECTIVE"
    CANCELLED = "CANCELLED"


class DeviationSeverity(StrEnum):
    MINOR = "MINOR"
    MAJOR = "MAJOR"
    CRITICAL = "CRITICAL"
    SYSTEMATIC_TREND = "SYSTEMATIC_TREND"


class DeviationType(StrEnum):
    CONCOMITANT_MED = "CONCOMITANT_MED"
    ELIGIBILITY = "ELIGIBILITY"
    GCP_COMPLIANCE = "GCP_COMPLIANCE"
    INFORMED_CONSENT = "INFORMED_CONSENT"
    INVESTIGATIONAL_PRODUCT = "INVESTIGATIONAL_PRODUCT"
    IP_MANAGEMENT = "IP_MANAGEMENT"
    LAB_SPECIMEN = "LAB_SPECIMEN"
    OTHER = "OTHER"
    PROTOCOL_PROCEDURE = "PROTOCOL_PROCEDURE"
    SAFETY_REPORTING = "SAFETY_REPORTING"
    VISIT_WINDOW = "VISIT_WINDOW"


class RCAMethodology(StrEnum):
    FIVE_WHYS = "FIVE_WHYS"
    HUMAN_FACTORS = "HUMAN_FACTORS"
    HYBRID = "HYBRID"
    ISHIKAWA_FISHBONE = "ISHIKAWA_FISHBONE"


class CAPAType(StrEnum):
    BOTH = "BOTH"
    CORRECTIVE = "CORRECTIVE"
    PREVENTIVE = "PREVENTIVE"


class EffectivenessOutcome(StrEnum):
    EFFECTIVE = "EFFECTIVE"
    INEFFECTIVE = "INEFFECTIVE"
    PARTIALLY_EFFECTIVE = "PARTIALLY_EFFECTIVE"
    PENDING = "PENDING"


class ActionItemStatus(StrEnum):
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"
    IN_PROGRESS = "IN_PROGRESS"
    OPEN = "OPEN"


class AuditType(StrEnum):
    FOR_CAUSE = "FOR_CAUSE"
    PROCESS_AUDIT = "PROCESS_AUDIT"
    SITE_AUDIT = "SITE_AUDIT"
    TMF_AUDIT = "TMF_AUDIT"
    VENDOR_QUALIFICATION = "VENDOR_QUALIFICATION"


class AuditStatus(StrEnum):
    CANCELLED = "CANCELLED"
    CAPA_PENDING = "CAPA_PENDING"
    COMPLETED = "COMPLETED"
    FINDINGS_REPORTED = "FINDINGS_REPORTED"
    IN_PROGRESS = "IN_PROGRESS"
    PLANNED = "PLANNED"


class FindingSeverity(StrEnum):
    CRITICAL = "CRITICAL"
    MAJOR = "MAJOR"
    MINOR = "MINOR"
    OBSERVATION = "OBSERVATION"


class RegulatoryAuthority(StrEnum):
    EMA = "EMA"
    FDA = "FDA"
    HEALTH_CANADA = "HEALTH_CANADA"
    MHRA = "MHRA"
    PMDA = "PMDA"


class BreachStatus(StrEnum):
    AUTHORITY_NOTIFIED = "AUTHORITY_NOTIFIED"
    CONFIRMED_BREACH = "CONFIRMED_BREACH"
    DISMISSED = "DISMISSED"
    RESOLVED = "RESOLVED"
    UNDER_EVALUATION = "UNDER_EVALUATION"


class RiskTier(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    LOW = "LOW"
    MEDIUM = "MEDIUM"


class RiskCategory(StrEnum):
    DATA_INTEGRITY = "DATA_INTEGRITY"
    OPERATIONAL_EXECUTION = "OPERATIONAL_EXECUTION"
    PATIENT_SAFETY = "PATIENT_SAFETY"
    REGULATORY_COMPLIANCE = "REGULATORY_COMPLIANCE"
