[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "apps-econsent"
version = "0.1.0"
description = "eConsent microservice"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.139.2,<0.140.0",
    "pydantic>=2.6.0",
    "sqlalchemy>=2.0.28",
    "sqlmodel>=0.0.39",
    "asyncpg>=0.29.0",
    "packages-database",
    "packages-security",
]

[tool.hatch.build.targets.wheel]
packages = [
    ".",
]
exclude = [
    "tests",
]

[tool.hatch.build.targets.wheel.sources]
"" = "apps/econsent"
