"""Pydantic schemas for cross-domain anomaly evaluation and candidate query adjudication.

Requirements: PRD-QRY-008
"""

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, Field

from apps.execution.domain.anomaly import CrossDomainAnomaly


class AdjudicationActionEnum(StrEnum):
    """Permitted adjudication actions."""

    APPROVE = "APPROVE"
    REJECT = "REJECT"


class AnomalyEvaluateRequest(BaseModel):
    """Request payload to trigger on-demand anomaly evaluation."""

    subject_id: str = Field(..., description="Subject identifier to evaluate.")
    study_id: str = Field(..., description="Study identifier.")
    enable_ai: bool = Field(
        default=True,
        description="Whether to run AI Gateway semantic reasoning if available.",
    )
    auto_stage_queries: bool = Field(
        default=True,
        description="Whether to automatically stage detected anomalies as CANDIDATE queries.",
    )


class AnomalyEvaluateResponse(BaseModel):
    """Response payload returning evaluation results."""

    subject_id: str
    study_id: str
    anomalies: list[CrossDomainAnomaly]
    evaluated_at: datetime
    queries_staged_count: int


class AnomalyCandidateItem(BaseModel):
    """Summary of a staged CANDIDATE query generated by the anomaly detector."""

    query_id: str
    study_id: str
    subject_id: str
    site_id: str | None = None
    visit_id: str | None = None
    domain: str | None = None
    test_code: str
    observation_id: str | None = None
    field_link: str | None = None
    rule_id: str | None = None
    message: str | None = None
    explanation: str | None = None
    origin: str | None = None
    priority: str | None = None
    status: str = "CANDIDATE"
    created_at: datetime
    created_by: str | None = None


class AdjudicationRequest(BaseModel):
    """Payload for Data Manager adjudication of a staged candidate query."""

    action: AdjudicationActionEnum = Field(
        ...,
        description="Adjudication decision: APPROVE (promote to OPEN) or REJECT (dismiss/CANCELLED).",
    )
    reason: str = Field(
        ...,
        min_length=5,
        description="Mandatory 21 CFR Part 11 justification or reason for change.",
    )
    updated_message: str | None = Field(
        default=None,
        description="Optional edited query text before opening to site staff.",
    )


class AdjudicationResponse(BaseModel):
    """Outcome of Data Manager candidate query adjudication."""

    query_id: str
    new_status: str
    action: str
    message: str
    adjudicated_by: str
    adjudicated_at: datetime
