"""Pre-compiled FHIR/LOINC to CDASH Laboratory (LB) ConceptMaps.

Requirements: PRD-CRF-007
"""

from apps.interop.domain.semantic_mapping_models import CDISCDomain, ConceptMapElement

LOINC_SYSTEM = "http://loinc.org"

LAB_TESTS_CONCEPT_MAP: list[ConceptMapElement] = [
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="2339-0",
        source_display="Glucose [Mass/volume] in Blood",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.GLUC",
        cdash_testcd="GLUC",
        cdash_test="Glucose",
        standard_unit="mg/dL",
        category="laboratory",
        description="Blood glucose concentration",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="2345-7",
        source_display="Glucose [Mass/volume] in Serum or Plasma",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.GLUC",
        cdash_testcd="GLUC",
        cdash_test="Glucose",
        standard_unit="mg/dL",
        category="laboratory",
        description="Serum or plasma glucose concentration",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="718-7",
        source_display="Hemoglobin [Mass/volume] in Blood",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.HGB",
        cdash_testcd="HGB",
        cdash_test="Hemoglobin",
        standard_unit="g/dL",
        category="laboratory",
        description="Whole blood hemoglobin level",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="6690-2",
        source_display="Leukocytes [#/volume] in Blood by Automated count",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.WBC",
        cdash_testcd="WBC",
        cdash_test="Leukocytes",
        standard_unit="10^3/uL",
        category="laboratory",
        description="White blood cell count",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="789-8",
        source_display="Erythrocytes [#/volume] in Blood by Automated count",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.RBC",
        cdash_testcd="RBC",
        cdash_test="Erythrocytes",
        standard_unit="10^6/uL",
        category="laboratory",
        description="Red blood cell count",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="777-3",
        source_display="Platelets [#/volume] in Blood by Automated count",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.PLAT",
        cdash_testcd="PLAT",
        cdash_test="Platelets",
        standard_unit="10^3/uL",
        category="laboratory",
        description="Platelet count",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="1742-6",
        source_display="Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.ALT",
        cdash_testcd="ALT",
        cdash_test="Alanine Aminotransferase",
        standard_unit="U/L",
        category="laboratory",
        description="Serum alanine aminotransferase (ALT / SGPT)",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="1920-8",
        source_display="Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.AST",
        cdash_testcd="AST",
        cdash_test="Aspartate Aminotransferase",
        standard_unit="U/L",
        category="laboratory",
        description="Serum aspartate aminotransferase (AST / SGOT)",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="2160-0",
        source_display="Creatinine [Mass/volume] in Serum or Plasma",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.CREAT",
        cdash_testcd="CREAT",
        cdash_test="Creatinine",
        standard_unit="mg/dL",
        category="laboratory",
        description="Serum creatinine level",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="1975-2",
        source_display="Bilirubin.total [Mass/volume] in Serum or Plasma",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.BILI",
        cdash_testcd="BILI",
        cdash_test="Bilirubin",
        standard_unit="mg/dL",
        category="laboratory",
        description="Total serum bilirubin",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="1751-7",
        source_display="Albumin [Mass/volume] in Serum or Plasma",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.ALB",
        cdash_testcd="ALB",
        cdash_test="Albumin",
        standard_unit="g/dL",
        category="laboratory",
        description="Serum albumin concentration",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="2823-3",
        source_display="Potassium [Moles/volume] in Serum or Plasma",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.K",
        cdash_testcd="K",
        cdash_test="Potassium",
        standard_unit="mmol/L",
        category="laboratory",
        description="Serum potassium electrolyte concentration",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="2951-2",
        source_display="Sodium [Moles/volume] in Serum or Plasma",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.SODIUM",
        cdash_testcd="SODIUM",
        cdash_test="Sodium",
        standard_unit="mmol/L",
        category="laboratory",
        description="Serum sodium electrolyte concentration",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="2093-3",
        source_display="Cholesterol [Mass/volume] in Serum or Plasma",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.CHOL",
        cdash_testcd="CHOL",
        cdash_test="Cholesterol",
        standard_unit="mg/dL",
        category="laboratory",
        description="Serum total cholesterol",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="2571-8",
        source_display="Triglyceride [Mass/volume] in Serum or Plasma",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.TRIG",
        cdash_testcd="TRIG",
        cdash_test="Triglycerides",
        standard_unit="mg/dL",
        category="laboratory",
        description="Serum triglycerides",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="4548-4",
        source_display="Hemoglobin A1c/Hemoglobin.total in Blood",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.HBA1C",
        cdash_testcd="HBA1C",
        cdash_test="Glycated Hemoglobin (HbA1c)",
        standard_unit="%",
        category="laboratory",
        description="Glycated hemoglobin percentage",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="3094-0",
        source_display="Urea nitrogen [Mass/volume] in Serum or Plasma",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.BUN",
        cdash_testcd="BUN",
        cdash_test="Blood Urea Nitrogen",
        standard_unit="mg/dL",
        category="laboratory",
        description="Blood urea nitrogen level",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="33914-3",
        source_display="Glomerular filtration rate/1.73 sq M.predicted",
        target_domain=CDISCDomain.LB,
        target_variable="eCRF.LB.EGFR",
        cdash_testcd="EGFR",
        cdash_test="Estimated Glomerular Filtration Rate",
        standard_unit="mL/min/1.73m2",
        category="laboratory",
        description="Estimated glomerular filtration rate (eGFR)",
    ),
]
