"""Pre-compiled FHIR/LOINC to CDASH Vital Signs (VS) ConceptMaps.

Requirements: PRD-CRF-007
"""

from apps.interop.domain.semantic_mapping_models import CDISCDomain, ConceptMapElement

LOINC_SYSTEM = "http://loinc.org"

VITAL_SIGNS_CONCEPT_MAP: list[ConceptMapElement] = [
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="8480-6",
        source_display="Systolic blood pressure",
        target_domain=CDISCDomain.VS,
        target_variable="eCRF.VS.SYSBP",
        cdash_testcd="SYSBP",
        cdash_test="Systolic Blood Pressure",
        standard_unit="mmHg",
        category="vital-signs",
        description="Systolic blood pressure in arterial system",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="8462-4",
        source_display="Diastolic blood pressure",
        target_domain=CDISCDomain.VS,
        target_variable="eCRF.VS.DIABP",
        cdash_testcd="DIABP",
        cdash_test="Diastolic Blood Pressure",
        standard_unit="mmHg",
        category="vital-signs",
        description="Diastolic blood pressure in arterial system",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="8867-4",
        source_display="Heart rate",
        target_domain=CDISCDomain.VS,
        target_variable="eCRF.VS.PULSE",
        cdash_testcd="PULSE",
        cdash_test="Pulse Rate",
        standard_unit="beats/min",
        category="vital-signs",
        description="Heart rate / pulse rate in beats per minute",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="8310-5",
        source_display="Body temperature",
        target_domain=CDISCDomain.VS,
        target_variable="eCRF.VS.TEMP",
        cdash_testcd="TEMP",
        cdash_test="Temperature",
        standard_unit="C",
        category="vital-signs",
        description="Body core or surface temperature",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="8331-1",
        source_display="Oral temperature",
        target_domain=CDISCDomain.VS,
        target_variable="eCRF.VS.TEMP",
        cdash_testcd="TEMP",
        cdash_test="Temperature",
        standard_unit="C",
        category="vital-signs",
        description="Oral body temperature",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="29463-7",  # deid: ignore
        source_display="Body weight",
        target_domain=CDISCDomain.VS,
        target_variable="eCRF.VS.WEIGHT",
        cdash_testcd="WEIGHT",
        cdash_test="Weight",
        standard_unit="kg",
        category="vital-signs",
        description="Body weight measured in kilograms",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="3141-9",
        source_display="Body weight Measured",
        target_domain=CDISCDomain.VS,
        target_variable="eCRF.VS.WEIGHT",
        cdash_testcd="WEIGHT",
        cdash_test="Weight",
        standard_unit="kg",
        category="vital-signs",
        description="Measured body weight",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="8302-2",
        source_display="Body height",
        target_domain=CDISCDomain.VS,
        target_variable="eCRF.VS.HEIGHT",
        cdash_testcd="HEIGHT",
        cdash_test="Height",
        standard_unit="cm",
        category="vital-signs",
        description="Body height measured in centimeters",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="8306-3",
        source_display="Body height --lying",
        target_domain=CDISCDomain.VS,
        target_variable="eCRF.VS.HEIGHT",
        cdash_testcd="HEIGHT",
        cdash_test="Height",
        standard_unit="cm",
        category="vital-signs",
        description="Recumbent body length / height",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="9279-1",
        source_display="Respiratory rate",
        target_domain=CDISCDomain.VS,
        target_variable="eCRF.VS.RESP",
        cdash_testcd="RESP",
        cdash_test="Respiratory Rate",
        standard_unit="breaths/min",
        category="vital-signs",
        description="Respiratory rate in breaths per minute",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="59408-5",
        source_display="Oxygen saturation in Arterial blood by Pulse oximetry",
        target_domain=CDISCDomain.VS,
        target_variable="eCRF.VS.SPO2",
        cdash_testcd="SPO2",
        cdash_test="Oxygen Saturation",
        standard_unit="%",
        category="vital-signs",
        description="Pulse oximetry arterial oxygen saturation",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="39156-5",
        source_display="Body mass index (BMI) [Ratio]",
        target_domain=CDISCDomain.VS,
        target_variable="eCRF.VS.BMI",
        cdash_testcd="BMI",
        cdash_test="Body Mass Index",
        standard_unit="kg/m2",
        category="vital-signs",
        description="Body Mass Index calculated ratio",
    ),
    ConceptMapElement(
        source_system=LOINC_SYSTEM,
        source_code="8478-0",
        source_display="Mean arterial pressure",
        target_domain=CDISCDomain.VS,
        target_variable="eCRF.VS.MAP",
        cdash_testcd="MAP",
        cdash_test="Mean Arterial Pressure",
        standard_unit="mmHg",
        category="vital-signs",
        description="Mean arterial blood pressure",
    ),
]
