/* tslint:disable */
/* eslint-disable */
/**
 * Auto-generated TypeScript interfaces representing the GxP clinical database models.
 * Excludes all internal compliance-only tables and audit logs.
 * Generated by scripts/introspect_pg_schema.py.
 */

export interface AllocationKeyMetadata {
  key_version: number;
  salt: string;
  created_at: string;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface BiostatExport {
  study_id: string;
  export_type: string;
  dataset_name?: string | null;
  status: string;
  error_message?: string | null;
  created_at: string;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface ChangeApprovalSignature {
  change_request_id: string;
  approver_id: string;
  signature_token: string;
  role: string;
  signed_at: string;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface ClinicalCodingAssignment {
  verbatim_text: string;
  source_field?: string | null;
  observation_id?: string | null;
  dictionary_type: "MEDDRA" | "WHODRUG" | "LOINC" | "SNOMED";
  dictionary_version: string;
  coded_code?: string | null;
  coded_term?: string | null;
  status: "UNCODED" | "SUGGESTED" | "CODED" | "AUTO_CODED" | "QUERY_PENDING" | "RECODING_REQUIRED";
  recoding_status: "NONE" | "PENDING" | "COMPLETED" | "CANCELLED";
  assigned_by?: string | null;
  assigned_at: string;
  score?: number | null;
  hierarchy?: Record<string, any> | null;
  suggestions?: Record<string, any> | null;
  domain?: string | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface ClinicalCodingLedger {
  assignment_id: string;
  verbatim_text: string;
  observation_id?: string | null;
  dictionary_type: "MEDDRA" | "WHODRUG" | "LOINC" | "SNOMED";
  old_dictionary_version?: string | null;
  old_coded_code?: string | null;
  old_coded_term?: string | null;
  new_dictionary_version: string;
  new_coded_code: string;
  new_coded_term: string;
  recoding_reason?: string | null;
  decision_by?: string | null;
  decision_at: string;
  old_hierarchy?: Record<string, any> | null;
  new_hierarchy?: Record<string, any> | null;
  recoding_status?: "NONE" | "PENDING" | "COMPLETED" | "CANCELLED" | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface ClinicalObservation {
  subject_id: string;
  study_id: string;
  site_id?: string | null;
  visit_id?: string | null;
  domain: string;
  observation_date: string;
  test_code: string;
  test_name: string;
  value?: number | null;
  value_string?: string | null;
  unit?: string | null;
  normalized_value?: number | null;
  normalized_unit?: string | null;
  is_outlier: boolean;
  is_sdv_verified: boolean;
  sdv_verified_by?: string | null;
  sdv_verified_at?: string | null;
  page_id?: string | null;
  is_sdv_flagged: boolean;
  sdv_flag_reason?: string | null;
  additional_properties?: Record<string, any> | null;
  protocol_version_tag?: string | null;
  protocol_version_index?: number | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface ClinicalQuery {
  study_id: string;
  site_id?: string | null;
  subject_id: string;
  visit_id?: string | null;
  domain?: string | null;
  test_code: string;
  status: string;
  explanation?: string | null;
  response?: string | null;
  created_at: string;
  updated_at: string;
  observation_id?: string | null;
  field_link?: string | null;
  message?: string | null;
  origin?: string | null;
  priority?: string | null;
  rule_id?: string | null;
  created_by?: string | null;
  responder?: string | null;
  resolver?: string | null;
  resolved_at?: string | null;
  cancellation_reason?: string | null;
  escalated_at?: string | null;
  form_id?: string | null;
  field_id?: string | null;
  query_type?: string | null;
  action_required?: string | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface ClinicalSubject {
  subject_id: string;
  study_id: string;
  site_id?: string | null;
  encrypted_demographics?: string | null;
  status: string;
  strat_factors?: Record<string, any> | null;
  is_unblinded: boolean;
  unblinded_at?: string | null;
  unblinded_by?: string | null;
  unblinded_reason?: string | null;
  unblinded_signature?: string | null;
  withdrawn_at?: string | null;
  withdrawal_reason?: string | null;
  randomization_id?: string | null;
  kit_reference?: string | null;
  enrollment_index?: number | null;
  treatment_group?: string | null;
  randomization_seed?: number | null;
  investigational_product_id?: string | null;
  active_protocol_version?: string | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface ClinicalVisit {
  subject_id: string;
  visit_name: string;
  visit_date: string;
  study_id: string;
  site_id?: string | null;
  protocol_version_tag?: string | null;
  protocol_version_index?: number | null;
  planned_date?: string | null;
  window_start?: string | null;
  window_end?: string | null;
  window_status?: string | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface ComplianceChangeRequest {
  setting_key: string;
  old_value?: string | null;
  new_value?: string | null;
  requested_by: string;
  reason: string;
  status: string;
  impact_assessment?: Record<string, any> | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface ComprehensionQuizResult {
  subject_id: string;
  site_id?: string | null;
  icf_version_id: string;
  score: number;
  passed: boolean;
  created_at: string;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface ConsentFormRecord {
  subject_id: string;
  site_id?: string | null;
  icf_version_id: string;
  printed_name?: string | null;
  relationship_to_subject?: string | null;
  signature_svg?: string | null;
  otp_auth_code?: string | null;
  status: string;
  signed_at?: string | null;
  is_verified: boolean;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface ConsentSignature {
  subject_id: string;
  site_id?: string | null;
  icf_version_id: string;
  printed_name: string;
  signature_svg_data?: string | null;
  signature_svg?: string | null;
  otp_auth_code?: string | null;
  meaning: string;
  cryptographic_token?: string | null;
  verification_hash?: string | null;
  signed_at?: string | null;
  timestamp: string;
  status: string;
  created_at?: string | null;
  created_by?: string | null;
  reason_for_change?: string | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface CtmsBudgetLineItem {
  id: string;
  grant_id: string;
  category: string;
  description: string;
  amount: number;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsClinicalQuery {
  id: string;
  study_id: string;
  site_id: string;
  visit_id?: string | null;
  status: string;
  explanation?: string | null;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsCountryRegulatoryMilestone {
  id: string;
  study_id: string;
  country_code: string;
  milestone_type: string;
  planned_date?: string | null;
  actual_date?: string | null;
  status: string;
  approval_number?: string | null;
  authority_name?: string | null;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsCraAllocation {
  id: string;
  cra_id: string;
  site_id: string;
  study_id: string;
  status: string;
  effective_start_date: string;
  effective_end_date?: string | null;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsDefeatedMonitoringVisit {
  id: string;
  visit_id: string;
  actual_date?: string | null;
  findings?: Record<string, any> | null;
  device_timestamp: string;
  offline_sync_markers: Record<string, any>;
  status: string;
  created_at: string;
  created_by?: string | null;
  reason_for_change?: string | null;
  version_index: number;
}

export interface CtmsDelegation {
  id: string;
  site_id: string;
  staff_user_id: string;
  task_codes: Record<string, any>;
  start_date: string;
  end_date?: string | null;
  is_active: boolean;
  signed_off: boolean;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsDeviationActionItem {
  id: string;
  deviation_id: string;
  site_id: string;
  description: string;
  assignee_user_id: string;
  assignee_role: string;
  due_date: string;
  status: string;
  resolution_notes?: string | null;
  completed_by?: string | null;
  completed_at?: string | null;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsEssentialDocument {
  id: string;
  study_id: string;
  site_id: string;
  document_type: string;
  file_name: string;
  file_hash: string;
  expiration_date?: string | null;
  status: string;
  review_notes?: string | null;
  reviewed_by?: string | null;
  reviewed_at?: string | null;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsEtmfSyncRecord {
  id: string;
  study_id: string;
  site_id: string;
  artifact_type: string;
  source_record_id: string;
  etmf_document_id: string;
  dia_zone: string;
  dia_section: string;
  dia_artifact: string;
  sync_status: string;
  error_message?: string | null;
  synced_at: string;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsFinancialInvoice {
  id: string;
  study_id: string;
  site_id: string;
  grant_id: string;
  invoice_number: string;
  invoice_type: string;
  gross_amount: number;
  withholding_amount: number;
  net_amount: number;
  currency: string;
  status: string;
  payable_ids: Record<string, any>;
  approved_by?: string | null;
  approved_at?: string | null;
  disbursed_at?: string | null;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsGeneratedLetter {
  id: string;
  visit_id: string;
  letter_type: string;
  rendered_content: string;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsInvestigatorGrant {
  id: string;
  study_id: string;
  site_id: string;
  total_budget: number;
  currency: string;
  status: string;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsInvestigatorPayable {
  id: string;
  grant_id: string;
  milestone_id?: string | null;
  amount: number;
  payment_status: string;
  due_date?: string | null;
  paid_at?: string | null;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsIpDestructionCertificate {
  id: string;
  study_id: string;
  site_id: string;
  certificate_number: string;
  kit_ids: Record<string, any>;
  destruction_method: string;
  destruction_date: string;
  witness_user_id: string;
  witness_role: string;
  pi_signature_hash: string;
  pi_signed_at: string;
  reason_for_destruction: string;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsIpKitRecord {
  id: string;
  study_id: string;
  site_id: string;
  kit_number: string;
  lot_number: string;
  kit_type: string;
  shipment_tracking_number: string;
  expiration_date: string;
  status: string;
  received_date?: string | null;
  dispensed_subject_id?: string | null;
  dispensed_visit_id?: string | null;
  dispensed_date?: string | null;
  returned_units_count?: number | null;
  expected_units_count?: number | null;
  compliance_percentage?: number | null;
  notes?: string | null;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsIpTemperatureExcursion {
  id: string;
  study_id: string;
  site_id: string;
  kit_ids: Record<string, any>;
  excursion_type: string;
  min_temp_celsius: number;
  max_temp_celsius: number;
  duration_hours: number;
  occurred_at: string;
  disposition_status: string;
  qa_reviewed_by?: string | null;
  qa_reviewed_at?: string | null;
  qa_rationale?: string | null;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsMonitoringVisitFinding {
  id: string;
  visit_id: string;
  text: string;
  severity: string;
  resolution_status: string;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
  offline_sync_markers?: Record<string, any> | null;
  sync_status?: string | null;
}

export interface CtmsMonitoringVisit {
  id: string;
  study_id: string;
  site_id: string;
  cra_id: string;
  visit_type: string;
  scheduled_date: string;
  actual_date?: string | null;
  status: string;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
  signature_manifestation?: Record<string, any> | null;
  signer?: string | null;
  signing_timestamp?: string | null;
  offline_sync_markers?: Record<string, any> | null;
  sync_status?: string | null;
}

export interface CtmsPaymentMilestone {
  id: string;
  grant_id: string;
  milestone_name: string;
  trigger_condition: string;
  amount: number;
  is_triggered: boolean;
  triggered_at?: string | null;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsProcedurePaymentGrid {
  id: string;
  grant_id: string;
  visit_name: string;
  procedure_code: string;
  procedure_name: string;
  base_amount: number;
  overhead_percentage: number;
  withholding_percentage: number;
  is_active: boolean;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsProtocolDeviation {
  id: string;
  study_id: string;
  site_id: string;
  subject_id?: string | null;
  visit_id?: string | null;
  deviation_category: string;
  severity: string;
  title: string;
  description: string;
  date_occurred: string;
  date_identified: string;
  status: string;
  root_cause_5whys: Record<string, any>;
  root_cause_summary?: string | null;
  corrective_action_plan?: string | null;
  preventive_action_plan?: string | null;
  quality_capa_id?: string | null;
  reported_by: string;
  resolved_by?: string | null;
  resolved_at?: string | null;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsRbqmKriMetric {
  id: string;
  study_id: string;
  site_id: string;
  metric_type: string;
  metric_value: number;
  threshold_low: number;
  threshold_high: number;
  breach_status: string;
  calculation_date: string;
  notes?: string | null;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsRecruitmentRecord {
  id: string;
  site_id: string;
  study_id: string;
  screened_count: number;
  enrolled_count: number;
  target_count: number;
  as_of_date: string;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsRegulatoryForm {
  id: string;
  study_id: string;
  site_id?: string | null;
  form_type: string;
  rendered_content: string;
  approval_status: string;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
  signature_manifestation?: Record<string, any> | null;
  signer?: string | null;
  signing_timestamp?: string | null;
}

export interface CtmsSiteGreenlightGate {
  id: string;
  study_id: string;
  site_id: string;
  overall_status: string;
  contract_approved: boolean;
  irb_approved: boolean;
  form_1572_approved: boolean;
  doa_signed_off: boolean;
  ip_ready: boolean;
  greenlight_certified_by?: string | null;
  greenlight_certified_at?: string | null;
  rejection_reason?: string | null;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsSiteMilestone {
  id: string;
  site_id: string;
  study_id: string;
  milestone_type: string;
  planned_date?: string | null;
  actual_date?: string | null;
  status: string;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsSiteRiskScore {
  id: string;
  study_id: string;
  site_id: string;
  composite_score: number;
  risk_level: string;
  assessment_date: string;
  recommended_monitoring_type: string;
  monitoring_interval_days: number;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface CtmsStudy {
  id: string;
  study_id: string;
  name: string;
  status: string;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
}

export interface DataLock {
  study_id?: string | null;
  site_id?: string | null;
  subject_id?: string | null;
  visit_id?: string | null;
  form_id?: string | null;
  item_group_id?: string | null;
  field_name?: string | null;
  scope_type: string;
  scope_id: string;
  lock_type: string;
  is_active: boolean;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  unlocked_at?: string | null;
  unlocked_by?: string | null;
  unlock_justification?: string | null;
  signature_token?: string | null;
  additional_metadata?: Record<string, any> | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface DictionaryImportJob {
  dictionary_type: "MEDDRA" | "WHODRUG" | "LOINC" | "SNOMED";
  dictionary_version: string;
  status: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
  started_at: string;
  completed_at?: string | null;
  progress_percentage: number;
  records_imported: number;
  errors_encountered: number;
  error_details?: string | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface DoaDelegationRecord {
  id: string;
  site_id: string;
  staff_user_id: string;
  task_code: string;
  start_date: string;
  end_date?: string | null;
  status: string;
  pi_signature_hash?: string | null;
  pi_approved_at?: string | null;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
  is_active: boolean;
  is_deleted: boolean;
}

export interface EisfDocumentRecord {
  id: string;
  site_id: string;
  study_id: string;
  section_code: string;
  filename: string;
  file_path: string;
  sha256_checksum: string;
  version_major: number;
  version_minor: number;
  status: string;
  expiration_date?: string | null;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
  is_active: boolean;
  is_deleted: boolean;
}

export interface EisfSectionTaxonomy {
  section_code: string;
  section_number: string;
  title: string;
  description: string;
  is_mandatory: boolean;
}

export interface FormSubmission {
  study_id: string;
  site_id?: string | null;
  subject_id: string;
  visit_id?: string | null;
  form_id: string;
  status: string;
  signature_manifest?: Record<string, any> | null;
  protocol_version?: string | null;
  payload?: Record<string, any> | null;
  is_active: boolean;
  is_readonly: boolean;
  cloned_from_id?: string | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface IpKit {
  study_id: string;
  kit_number: string;
  kit_type: string;
  description?: string | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface IsfDocument {
  id: string;
  study_id: string;
  site_id: string;
  binder_classification: string;
  filename: string;
  object_key?: string | null;
  content?: string | null;
  mime_type: string;
  version_index: number;
  issue_date?: string | null;
  expiration_date?: string | null;
  document_owner_id?: string | null;
  created_at: string;
  created_by: string;
  metadata_json?: Record<string, any> | null;
  correlation_key?: string | null;
  content_checksum?: string | null;
  sync_status: string;
  source_system: string;
}

export interface KitDispensation {
  study_id: string;
  subject_id: string;
  kit_id: string;
  site_id: string;
  visit_id: string;
  quantity: number;
  timestamp: string;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface LabReferenceRange {
  study_id: string;
  test_code: string;
  test_name: string;
  lab_source: string;
  site_id?: string | null;
  unit?: string | null;
  normalized_unit?: string | null;
  sex?: string | null;
  age_low?: number | null;
  age_high?: number | null;
  range_low?: number | null;
  range_high?: number | null;
  critical_low?: number | null;
  critical_high?: number | null;
  created_at?: string | null;
  created_by?: string | null;
  reason_for_change?: string | null;
  version_index?: number | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface LabTestMasterLegacy {
  study_id: string;
  test_code: string;
  test_name: string;
  default_unit?: string | null;
  normalized_unit?: string | null;
  loinc_code?: string | null;
  created_at?: string | null;
  created_by?: string | null;
  reason_for_change?: string | null;
  version_index?: number | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface LabTestMaster {
  study_id: string;
  test_code: string;
  test_name: string;
  default_unit: string;
  normalized_unit: string;
  loinc_code?: string | null;
  created_at?: string | null;
  created_by?: string | null;
  reason_for_change?: string | null;
  version_index: number;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface LabUnitConversion {
  study_id: string;
  test_code: string;
  from_unit: string;
  to_unit: string;
  factor: number;
  offset?: number | null;
  created_at?: string | null;
  created_by?: string | null;
  reason_for_change?: string | null;
  version_index?: number | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface MeddraHierarchy {
  dictionary_version: string;
  llt_code: string;
  pt_code: string;
  hlt_code: string;
  hlgt_code: string;
  soc_code: string;
  primary_soc_flag?: string | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface MedDRATerm {
  dictionary_version: string;
  code: string;
  term_name: string;
  level: string;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface MigrationRule {
  study_id: string;
  source_version: string;
  target_version: string;
  rule_type: string;
  source_field?: string | null;
  target_field?: string | null;
  default_value_string?: string | null;
  default_value_float?: number | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface RandomizationConfig {
  study_id: string;
  algorithm_type: string;
  arms_ratios: Record<string, any>;
  stratification_factors?: Record<string, any> | null;
  encrypted_block_config?: string | null;
  seed?: number | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface ResupplyEvent {
  study_id: string;
  site_id: string;
  kit_id: string;
  requested_qty: number;
  status: string;
  triggered_at: string;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface SdtmDomainRecord {
  study_id: string;
  domain: string;
  usubjid: string;
  record_data: Record<string, any>;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface SDVSignOff {
  scope: string;
  target_id: string;
  subject_id: string;
  study_id: string;
  site_id?: string | null;
  is_verified: boolean;
  verified_by?: string | null;
  verified_at?: string | null;
  dropped_reason?: string | null;
  dropped_at?: string | null;
  status: string;
  flagged_by?: string | null;
  flagged_at?: string | null;
  flag_reason?: string | null;
  flag_severity?: string | null;
  resolved_by?: string | null;
  resolved_at?: string | null;
  created_at?: string | null;
  created_by?: string | null;
  reason_for_change?: string | null;
  version_index: number;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface SiteComplianceCache {
  study_id: string;
  site_id?: string | null;
  milestone: string;
  is_complete: boolean;
  missing_documents?: string | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface SiteInventory {
  study_id: string;
  site_id: string;
  kit_id: string;
  on_hand_qty: number;
  reorder_threshold: number;
  resupply_signal: boolean;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface SiteStaffMember {
  id: string;
  site_id: string;
  user_id: string;
  first_name: string;
  last_name: string;
  email: string;
  primary_role: string;
  license_number?: string | null;
  gcp_certified: boolean;
  created_at: string;
  created_by: string;
  reason_for_change: string;
  version_index: number;
  is_active: boolean;
  is_deleted: boolean;
}

export interface StratumState {
  study_id: string;
  stratum_key: string;
  block_index: number;
  encrypted_sequence?: string | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface StudyAuthoredRule {
  study_id: string;
  rule_id: string;
  rule_type: string;
  condition: Record<string, any>;
  query_message: string;
  message: string;
  publication_version: string;
  is_active: boolean;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface SubjectConsent {
  subject_id: string;
  study_id: string;
  site_id?: string | null;
  version_tag: string;
  version_index: number;
  protocol_version?: string | null;
  status: string;
  icf_signed: boolean;
  icf_signed_date?: string | null;
  requires_reconsent: boolean;
  is_paper_override: boolean;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface SubjectRandomization {
  study_id: string;
  site_id?: string | null;
  subject_id: string;
  stratum_key?: string | null;
  encrypted_allocation: string;
  kit_reference?: string | null;
  randomized_at: string;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface TSDVConfig {
  study_id: string;
  sampling_model: string;
  initial_full_sdv_subject_count: number;
  random_sample_percentage: number;
  full_sdv_domains?: Record<string, any> | null;
  safety_endpoints?: Record<string, any> | null;
  zero_sdv_domains?: Record<string, any> | null;
  trial_random_seed?: number | null;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface WhodrugAtc {
  dictionary_version: string;
  atc_code: string;
  description: string;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface WhodrugDrugAtc {
  dictionary_version: string;
  drug_code: string;
  atc_code: string;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface WhodrugDrugIngredient {
  dictionary_version: string;
  drug_code: string;
  ingredient_code: string;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface WhodrugIngredient {
  dictionary_version: string;
  ingredient_code: string;
  ingredient_name: string;
  id: string;
  version: number;
  is_deleted: boolean;
}

export interface WHODrugRecord {
  dictionary_version: string;
  drug_code: string;
  preferred_name: string;
  drug_name?: string | null;
  id: string;
  version: number;
  is_deleted: boolean;
}
