"""Initial baseline

Revision ID: c040ea61d4c3
Revises: None
Create Date: 2026-08-04 13:05:27.300029

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c040ea61d4c3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quality_audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("user_role", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("details", sa.String(length=1000), nullable=False),
        sa.Column("record_id", sa.String(length=255), nullable=True),
        sa.Column("change_reason", sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quality_audit_logs_timestamp"),
        "quality_audit_logs",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quality_audit_logs_user_id"),
        "quality_audit_logs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "quality_deviations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=255), nullable=False),
        sa.Column("site_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("is_protocol_violation", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quality_deviations_site_id"),
        "quality_deviations",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quality_deviations_study_id"),
        "quality_deviations",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "quality_root_cause_analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("deviation_id", sa.String(length=36), nullable=False),
        sa.Column("methodology", sa.String(length=255), nullable=False),
        sa.Column("investigation_details", sa.String(), nullable=False),
        sa.Column("root_cause_summary", sa.String(), nullable=False),
        sa.Column("study_id", sa.String(length=255), nullable=False),
        sa.Column("site_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.ForeignKeyConstraint(
            ["deviation_id"], ["quality_deviations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quality_root_cause_analyses_deviation_id"),
        "quality_root_cause_analyses",
        ["deviation_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_quality_root_cause_analyses_site_id"),
        "quality_root_cause_analyses",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quality_root_cause_analyses_study_id"),
        "quality_root_cause_analyses",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "quality_capa_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("deviation_id", sa.String(length=36), nullable=False),
        sa.Column("rca_id", sa.String(length=36), nullable=True),
        sa.Column("capa_type", sa.String(length=50), nullable=False),
        sa.Column("action_plan", sa.String(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("preventive_measures", sa.String(), nullable=True),
        sa.Column("target_completion_date", sa.DateTime(), nullable=True),
        sa.Column("study_id", sa.String(length=255), nullable=False),
        sa.Column("site_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.ForeignKeyConstraint(
            ["deviation_id"], ["quality_deviations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["rca_id"], ["quality_root_cause_analyses.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quality_capa_records_deviation_id"),
        "quality_capa_records",
        ["deviation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quality_capa_records_rca_id"),
        "quality_capa_records",
        ["rca_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quality_capa_records_site_id"),
        "quality_capa_records",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quality_capa_records_study_id"),
        "quality_capa_records",
        ["study_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_quality_capa_records_study_id"), table_name="quality_capa_records"
    )
    op.drop_index(
        op.f("ix_quality_capa_records_site_id"), table_name="quality_capa_records"
    )
    op.drop_index(
        op.f("ix_quality_capa_records_rca_id"), table_name="quality_capa_records"
    )
    op.drop_index(
        op.f("ix_quality_capa_records_deviation_id"), table_name="quality_capa_records"
    )
    op.drop_table("quality_capa_records")
    op.drop_index(
        op.f("ix_quality_root_cause_analyses_study_id"),
        table_name="quality_root_cause_analyses",
    )
    op.drop_index(
        op.f("ix_quality_root_cause_analyses_site_id"),
        table_name="quality_root_cause_analyses",
    )
    op.drop_index(
        op.f("ix_quality_root_cause_analyses_deviation_id"),
        table_name="quality_root_cause_analyses",
    )
    op.drop_table("quality_root_cause_analyses")
    op.drop_index(
        op.f("ix_quality_deviations_study_id"), table_name="quality_deviations"
    )
    op.drop_index(
        op.f("ix_quality_deviations_site_id"), table_name="quality_deviations"
    )
    op.drop_table("quality_deviations")
    op.drop_index(
        op.f("ix_quality_audit_logs_user_id"), table_name="quality_audit_logs"
    )
    op.drop_index(
        op.f("ix_quality_audit_logs_timestamp"), table_name="quality_audit_logs"
    )
    op.drop_table("quality_audit_logs")
    # ### end Alembic commands ###
