#!/usr/bin/env bash
#
# Interactive Credential Bootstrapping Wizard for Cadence Clinical
# Generated by the /wizard skill and conforming to Matt Pocock's wizard standard.
#
# Walks a human through generating 256-bit GxP cryptographic keys,
# configuring third-party dashboards (AI, S3 storage), upserting .env,
# and syncing secrets to GitHub Actions.
#

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard Library (Consistent UX Engine)
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1); CYAN=$(tput setaf 6)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""; CYAN=""
fi

TOTAL_STAGES=7
_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()
SYNC_GH=0
DEPLOY_MODE="local-dev"
AUTO_ACCEPT="${CADENCE_WIZARD_AUTO_ACCEPT:-0}"

# Handle CLI flags
for arg in "$@"; do
  case "$arg" in
    --dev|--non-interactive)
      AUTO_ACCEPT=1
      ;;
    --env-file=*)
      ENV_FILE="${arg#*=}"
      ;;
    -h|--help)
      printf "Usage: %s [--dev] [--env-file=.env] [--help]\n" "$0"
      printf "  --dev, --non-interactive  Run in automated local development mode (auto-generate all keys)\n"
      printf "  --env-file=PATH           Target environment file (default: .env)\n"
      exit 0
      ;;
  esac
done

_clear() {
  [[ -t 1 ]] || return 0
  if [[ "$AUTO_ACCEPT" == "1" ]]; then return 0; fi
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  Cadence Clinical — Credential & Environment Wizard%s\n' "$BOLD" "$BLUE" "$RESET"
  printf '%s  %s stages · Multi-Tier Setup (Local Dev & Staging/Prod)%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  This wizard guides you through generating Part 11 cryptographic keys,\n' "$DIM"
  printf '  configuring third-party cloud integrations (AI, S3 storage), and\n'
  printf '  synchronizing repository secrets. Safe to re-run anytime.%s\n\n' "$RESET"
  if [[ "$AUTO_ACCEPT" != "1" ]]; then
    pause "Ready to start setup?"
  fi
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n\n' "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()   { printf '  %s\n' "$1"; }
step()  { printf '  %s•%s %s\n' "$CYAN" "$RESET" "$1"; }
note()  { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn()  { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
success(){ printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }

open_url() {
  local url="$1"
  if [[ "$AUTO_ACCEPT" == "1" ]]; then
    note "Dashboard URL: $url"
    return 0
  fi
  printf '  %s↗ Opening dashboard:%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "Could not open browser automatically. Visit manually: $url"; fi
  } >/dev/null 2>&1 || warn "Could not open browser automatically. Visit manually: $url"
}

pause() {
  if [[ "$AUTO_ACCEPT" == "1" ]]; then return 0; fi
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  if [[ "$AUTO_ACCEPT" == "1" ]]; then return 0; fi
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

gen_secret_256() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null
  else
    # Fallback via urandom
    head -c 32 /dev/urandom | od -A n -v -t x1 | tr -d ' \n'
  fi
}

ask() {
  local key="$1" prompt="$2" default_val="${3:-}" current input
  current=$(_existing "$key" || true)
  [[ -z "$current" && -n "$default_val" ]] && current="$default_val"

  if [[ "$AUTO_ACCEPT" == "1" ]]; then
    printf -v "$key" '%s' "$current"
    return 0
  fi

  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" default_val="${3:-}" current input
  current=$(_existing "$key" || true)
  [[ -z "$current" && -n "$default_val" ]] && current="$default_val"

  if [[ "$AUTO_ACCEPT" == "1" ]]; then
    printf -v "$key" '%s' "$current"
    return 0
  fi

  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current secret]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_or_generate_key() {
  local key="$1" desc="$2" generated current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    if [[ "$AUTO_ACCEPT" == "1" ]]; then
      write_env "$key" "$current"
      return 0
    fi
    printf '  %s%s%s: %s[Enter keeps existing key]%s ' "$BOLD" "$desc ($key)" "$RESET" "$DIM" "$RESET"
    read -rs input || true
    printf '\n'
    [[ -z "$input" ]] && input="$current"
  else
    generated=$(gen_secret_256)
    if [[ "$AUTO_ACCEPT" == "1" ]]; then
      input="$generated"
    else
      say "$desc"
      note "Generated 256-bit entropy token: ${generated:0:8}...${generated: -8}"
      printf '  %sAccept generated key?%s %s[Enter to accept, or paste custom]%s ' "$BOLD" "$RESET" "$DIM" "$RESET"
      read -rs input || true
      printf '\n'
      [[ -z "$input" ]] && input="$generated"
    fi
  fi
  write_env "$key" "$input"
  if [[ "$SYNC_GH" == "1" ]]; then
    set_secret "$key" "$input"
  fi
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ synced%s GitHub Actions secret: %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set manually via gh secret set $name)")
  warn "Skipped GitHub secret $name: gh CLI not authenticated"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup Complete!%s\n\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "Persisted ${#WRITTEN_ENV[@]} configuration key(s) to $ENV_FILE"
  (( ${#WRITTEN_SECRET[@]} )) && note "Synchronized ${#WRITTEN_SECRET[@]} secret(s) to GitHub Actions"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "Manual follow-up items remaining:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES (Declarative Setup Workflow)
# ──────────────────────────────────────────────────────────────────────────

banner

# ── Stage 1: Deployment Tier & Target File ─────────────────────────────────
stage "Target Tier & Environment File"
say "Select your target deployment profile and environment file."
note "Target file: $ENV_FILE"

if [[ "$AUTO_ACCEPT" == "1" ]]; then
  DEPLOY_MODE="local-dev"
else
  printf '  %s1)%s Local Development (fast-path, local SQLite/Postgres defaults)\n' "$CYAN" "$RESET"
  printf '  %s2)%s Staging / Production (explicit cloud integrations & strict verification)\n' "$CYAN" "$RESET"
  printf '  %sSelect mode [1/2, default 1]:%s ' "$BOLD" "$RESET"
  read -r mode_input || true
  if [[ "$mode_input" == "2" ]]; then
    DEPLOY_MODE="staging-prod"
  else
    DEPLOY_MODE="local-dev"
  fi
fi

say "Active Mode: $BOLD$DEPLOY_MODE$RESET"
write_env "APP_ENV" "$([[ "$DEPLOY_MODE" == "staging-prod" ]] && echo "production" || echo "development")"
write_env "CADENCE_TEST_MODE" "false"
write_env "DEBUG" "$([[ "$DEPLOY_MODE" == "staging-prod" ]] && echo "false" || echo "true")"
write_env "LOG_LEVEL" "INFO"
write_env "BRAND_NAME" "Cadence Clinical Research Software"
write_env "BRAND_DOMAIN" "ccrsoft.com"

# ── Stage 2: GitHub Actions CI Secret Sync ─────────────────────────────────
stage "GitHub Actions CI/CD Synchronization"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  success "GitHub CLI (gh) detected and authenticated."
  if confirm "Synchronize generated cryptographic keys to GitHub Actions repository secrets?"; then
    SYNC_GH=1
    say "GitHub Actions secret mirroring enabled."
  else
    say "GitHub Actions sync skipped (local-only)."
  fi
else
  note "GitHub CLI (gh) not authenticated. Secrets will only be written to $ENV_FILE."
fi

# ── Stage 3: GxP Cryptographic Keys (21 CFR Part 11) ──────────────────────
stage "GxP Cryptographic Security Keys"
say "Generating 256-bit cryptographic keys required for Part 11 signatures, audit trails, and inter-service HMAC."

ask_or_generate_key "GATEWAY_SECRET" "Inter-service HMAC-SHA256 Gateway signature secret"
ask_or_generate_key "AUDIT_LOG_SECRET_KEY" "21 CFR Part 11 immutable audit trail hashing key"
ask_or_generate_key "SIGNING_SECRET" "Protocol authoring & electronic document digital seals key"
ask_or_generate_key "SAFETY_SALT" "SUSAR / SAE safety reporting de-identification salt"
ask_or_generate_key "INBOUND_EMAIL_HMAC_SECRET" "eTMF inbound email verification & webhook secret"

# ── Stage 4: Document Storage & Archival ──────────────────────────────────
stage "Document Storage & Regulatory Archival"
if [[ "$DEPLOY_MODE" == "local-dev" ]]; then
  say "Local development uses filesystem object storage (./storage)."
  write_env "STORAGE_BACKEND" "local"
  write_env "STORAGE_LOCAL_DIR" "./storage"
  mkdir -p ./storage
else
  say "Configure AWS S3 or MinIO object storage for regulatory document archives."
  open_url "https://console.aws.amazon.com/iam/home#/security_credentials"
  ask AWS_ACCESS_KEY_ID "AWS Access Key ID:"
  ask_secret AWS_SECRET_ACCESS_KEY "AWS Secret Access Key:"
  ask S3_BUCKET_NAME "S3 Bucket Name:" "cadence-clinical-etmf-prod"
  ask AWS_REGION "AWS Region:" "us-east-1"
  write_env "STORAGE_BACKEND" "s3"
  write_env "AWS_ACCESS_KEY_ID" "$AWS_ACCESS_KEY_ID"
  write_env "AWS_SECRET_ACCESS_KEY" "$AWS_SECRET_ACCESS_KEY"
  write_env "S3_BUCKET_NAME" "$S3_BUCKET_NAME"
  write_env "AWS_REGION" "$AWS_REGION"
fi

# ── Stage 5: AI & LLM Ingestion Services ─────────────────────────────────
stage "AI Digitization & LLM Ingestion"
say "Select your LLM inference provider for automated protocol digitization and AI gateway."

if [[ "$AUTO_ACCEPT" == "1" ]]; then
  write_env "LLM_API_ENDPOINT" "https://generativelanguage.googleapis.com/v1beta/openai/"
else
  printf '  %s1)%s Google Gemini (Google AI Studio - Recommended for USDM digitization)\n' "$CYAN" "$RESET"
  printf '  %s2)%s OpenAI (GPT-4o)\n' "$CYAN" "$RESET"
  printf '  %s3)%s Anthropic Claude\n' "$CYAN" "$RESET"
  printf '  %s4)%s Local Ollama\n' "$CYAN" "$RESET"
  printf '  %s5)%s Skip AI configuration for now\n' "$CYAN" "$RESET"
  printf '  %sSelect provider [1-5, default 1]:%s ' "$BOLD" "$RESET"
  read -r ai_choice || true
  case "${ai_choice:-1}" in
    1)
      open_url "https://aistudio.google.com/app/apikey"
      step "Click 'Create API key' in Google AI Studio and copy it."
      ask_secret LLM_API_KEY "Paste your Gemini API Key:"
      write_env "LLM_API_KEY" "$LLM_API_KEY"
      write_env "LLM_API_ENDPOINT" "https://generativelanguage.googleapis.com/v1beta/openai/"
      ;;
    2)
      open_url "https://platform.openai.com/api-keys"
      step "Create a new secret key in the OpenAI developer console."
      ask_secret LLM_API_KEY "Paste your OpenAI API Key:"
      write_env "LLM_API_KEY" "$LLM_API_KEY"
      write_env "LLM_API_ENDPOINT" "https://api.openai.com/v1"
      ;;
    3)
      open_url "https://console.anthropic.com/settings/keys"
      step "Create an API key in the Anthropic console."
      ask_secret LLM_API_KEY "Paste your Anthropic API Key:"
      write_env "LLM_API_KEY" "$LLM_API_KEY"
      write_env "LLM_API_ENDPOINT" "https://api.anthropic.com/v1"
      ;;
    4)
      say "Configuring for local Ollama OpenAI-compatible endpoint."
      write_env "LLM_API_KEY" "ollama-local"
      write_env "LLM_API_ENDPOINT" "http://localhost:11434/v1"
      ;;
    *)
      say "Skipping external AI API key configuration."
      ;;
  esac
fi

# ── Stage 6: Identity Provider & SMTP Notifications ───────────────────────
stage "Identity Provider (Keycloak) & SMTP Transport"
if [[ "$DEPLOY_MODE" == "local-dev" ]]; then
  say "Writing local Keycloak OIDC and MailHog SMTP defaults."
  write_env "KEYCLOAK_URL" "http://localhost:8080"
  write_env "KEYCLOAK_REALM" "cadence"
  write_env "KEYCLOAK_CLIENT_ID" "cadence-clinical"
  write_env "KEYCLOAK_ADMIN" "admin"
  write_env "KEYCLOAK_ADMIN_PASSWORD" "admin_password"
  write_env "JWT_ALGORITHM" "RS256"
  write_env "SMTP_HOST" "localhost"
  write_env "SMTP_PORT" "1025"
  write_env "SMTP_USERNAME" "dev_user"
  write_env "SMTP_PASSWORD" "dev_password"
  write_env "SMTP_SENDER" "no-reply@ccrsoft.com"
  write_env "SMTP_USE_TLS" "false"
  write_env "SMTP_USE_SSL" "false"
else
  ask KEYCLOAK_URL "Keycloak Base URL:" "https://auth.ccrsoft.com"
  ask KEYCLOAK_REALM "Keycloak Realm:" "cadence"
  ask KEYCLOAK_CLIENT_ID "Keycloak Client ID:" "cadence-clinical"
  ask_secret KEYCLOAK_ADMIN_PASSWORD "Keycloak Admin Password:"
  write_env "KEYCLOAK_URL" "$KEYCLOAK_URL"
  write_env "KEYCLOAK_REALM" "$KEYCLOAK_REALM"
  write_env "KEYCLOAK_CLIENT_ID" "$KEYCLOAK_CLIENT_ID"
  write_env "KEYCLOAK_ADMIN_PASSWORD" "$KEYCLOAK_ADMIN_PASSWORD"

  ask SMTP_HOST "SMTP Host:" "smtp.sendgrid.net"
  ask SMTP_PORT "SMTP Port:" "587"
  ask SMTP_USERNAME "SMTP Username:" "apikey"
  ask_secret SMTP_PASSWORD "SMTP API Key / Password:"
  ask SMTP_SENDER "SMTP From Address:" "no-reply@ccrsoft.com"
  write_env "SMTP_HOST" "$SMTP_HOST"
  write_env "SMTP_PORT" "$SMTP_PORT"
  write_env "SMTP_USERNAME" "$SMTP_USERNAME"
  write_env "SMTP_PASSWORD" "$SMTP_PASSWORD"
  write_env "SMTP_SENDER" "$SMTP_SENDER"
  write_env "SMTP_USE_TLS" "true"
fi

# ── Stage 7: Database Connection URLs & Doctor Sentinel ───────────────────
stage "Database URLs & Environment Verification"
say "Configuring database connection strings for all clinical engines."

write_env "NEO4J_URI" "bolt://localhost:7687"
write_env "NEO4J_USER" "neo4j"
write_env "NEO4J_PASSWORD" "cadence_password"
write_env "DATABASE_URL" "postgresql+asyncpg://cadence:cadence_password@localhost:5432/cadence_edc"
write_env "ETMF_DATABASE_URL" "postgresql+asyncpg://cadence:cadence_password@localhost:5433/cadence_etmf"
write_env "CTMS_DATABASE_URL" "postgresql+asyncpg://cadence:cadence_password@localhost:5434/cadence_ctms"
write_env "QUALITY_DATABASE_URL" "postgresql+asyncpg://cadence:cadence_password@localhost:5435/cadence_quality"
write_env "ORG_DATABASE_URL" "postgresql+asyncpg://cadence:cadence_password@localhost:5432/cadence_edc"

write_env "SAFETY_DATABASE_URL" "sqlite+aiosqlite:///safety.db"
write_env "INTEROP_DATABASE_URL" "sqlite+aiosqlite:///interop.db"
write_env "TICKETS_DATABASE_URL" "sqlite+aiosqlite:///tickets.db"
write_env "NOTIFICATIONS_DATABASE_URL" "sqlite+aiosqlite:///notifications.db"
write_env "ECONSENT_DATABASE_URL" "sqlite+aiosqlite:///econsent.db"
write_env "EISF_DATABASE_URL" "sqlite+aiosqlite:///eisf.db"

finish

if confirm "Run 'cadence doctor --auto-fix' to validate ports and initialize schemas now?"; then
  if command -v uv >/dev/null 2>&1; then
    uv run cadence doctor --auto-fix || true
  fi
fi
