"""
Schema Validation Tool for Active CI Verification.

This script imports all downstream services statically to compile and aggregate
their OpenAPI schemas. It verifies that all schemas are correctly namespaced using
service-specific prefixes, preventing naming collisions or model overwrites in the
unified gateway schema. It fails the build if any non-namespaced schema definitions
overlap or collide.

Compliance:
- Gate 1: Fully documented and typed.
- Gate 3: Executed as part of continuous integration checks.
"""

import importlib
import os
import sys
from pathlib import Path
from typing import Any

# Add repository root to sys.path
app_root = str(Path(__file__).resolve().parent.parent)
if app_root not in sys.path:
    sys.path.insert(0, app_root)

# Enforce Python 3.14+ runtime before loading standard modules or packages
if sys.version_info < (3, 14):
    try:
        from scripts.runtime_guard import enforce_python_runtime

        enforce_python_runtime()
    except Exception:
        sys.stderr.write(
            f"[FATAL] Incompatible Python runtime {sys.version.split()[0]} ({sys.executable}).\n"
            "Cadence Clinical requires Python 3.14+.\n"
            "Please run: uv run python scripts/validate_schemas.py\n"
        )
        sys.exit(1)

from scripts.runtime_guard import enforce_python_runtime, print_runtime_info

# Prevent import errors due to missing secret keys in offline environment
os.environ.setdefault(
    "AUDIT_LOG_SECRET_KEY",
    "test-gxp-audit-secret-key-placeholder-abc",  # pragma: allowlist secret
)
os.environ.setdefault(
    "INBOUND_EMAIL_HMAC_SECRET",
    "test-email-hmac-secret-placeholder-xyz",  # pragma: allowlist secret
)
os.environ.setdefault(
    "GATEWAY_SECRET",
    "test-gateway-secret-placeholder-123",  # pragma: allowlist secret
)

packages_dir = os.path.join(app_root, "packages")
for name in ["database", "deid", "security", "ui"]:
    pkg_path = os.path.join(packages_dir, name)
    if pkg_path not in sys.path:
        sys.path.insert(0, pkg_path)


# Track dynamic import errors for diagnostic reporting
IMPORT_ERRORS: list[tuple[str, Exception]] = []


def discover_services() -> dict[str, dict[str, Any]]:
    """Dynamically scan apps directory and load microservices with their API configurations."""
    config = {}
    apps_dir = os.path.join(app_root, "apps")
    if not os.path.isdir(apps_dir):
        return config

    # Scan subdirectories under apps/
    for name in sorted(os.listdir(apps_dir)):
        dir_path = os.path.join(apps_dir, name)
        # Exclude gateway aggregator, non-directories, and hidden files/folders
        if name == "gateway" or name.startswith(".") or not os.path.isdir(dir_path):
            continue

        # Check for main.py entrypoint containing FastAPI application object
        main_path = os.path.join(dir_path, "main.py")
        if not os.path.isfile(main_path):
            continue

        # Dynamically load the module using Python's standard dynamic import machinery
        try:
            module = importlib.import_module(f"apps.{name}.main")
            app = getattr(module, "app", None)
            if app is not None:
                # Decide prefix
                prefix = "ETMF_" if name == "etmf" else f"{name.capitalize()}_"
                config[name] = {"app": app, "prefix": prefix}
        except Exception as e:
            print(f"Error dynamically importing service '{name}': {e}", file=sys.stderr)
            IMPORT_ERRORS.append((name, e))

    return config


# Map downstream service identifiers to their corresponding FastAPI apps and gateway prefixes
SERVICES_CONFIG = discover_services()


def validate_schemas() -> bool:
    """
    Compile and validate all schemas from downstream microservices.

    Retrieves the OpenAPI specification dynamically generated by each service,
    checks for duplicates, and simulates the unified aggregation to detect
    any namespacing errors or naming collisions.

    Returns:
        bool: True if the schema compilation and namespaces are 100% correct and
              safe from collisions; False otherwise.
    """
    print_runtime_info("validate_schemas.py")
    print("--- Starting Static Schema Compilation & Namespacing Checks ---")

    if IMPORT_ERRORS:
        print(
            "\n[VALIDATION FAILED] Static compilation of downstream services failed:",
            file=sys.stderr,
        )
        for name, err in IMPORT_ERRORS:
            print(f"  - Service '{name}' import failed: {err}", file=sys.stderr)
        print(
            "\nTroubleshooting Reference: Please refer to CONTRIBUTING.md#schema-validation-failures "
            "for instructions on how to resolve service import failures.",
            file=sys.stderr,
        )
        return False

    raw_schemas: dict[str, Any] = {}

    # 1. Statically generate the OpenAPI schema from each application instance
    for service_name, config in SERVICES_CONFIG.items():
        try:
            raw_schemas[service_name] = config["app"].openapi()
            print(f"Successfully compiled schema for '{service_name}' offline.")
        except Exception as e:
            print(f"Error compiling OpenAPI for {service_name}: {e}", file=sys.stderr)
            print(
                "\nTroubleshooting Reference: Please refer to CONTRIBUTING.md#schema-validation-failures "
                "for instructions on how to resolve schema compilation failures.",
                file=sys.stderr,
            )
            return False

    # 2. Track schema definition occurrences across services to find shared models
    schema_sources: dict[str, list[str]] = {}
    for service_name, spec in raw_schemas.items():
        schemas = spec.get("components", {}).get("schemas", {})
        for schema_name in schemas:
            schema_sources.setdefault(schema_name, []).append(service_name)

    # Report overlapping model definitions
    overlapping_schemas = {
        name: srcs for name, srcs in schema_sources.items() if len(srcs) > 1
    }
    if overlapping_schemas:
        print(
            f"\nFound {len(overlapping_schemas)} model names shared across multiple services:"
        )
        for name, services in overlapping_schemas.items():
            print(f"  - Model '{name}' is defined in: {', '.join(services)}")
    else:
        print("\nNo overlapping raw model names detected across services.")

    # 3. Simulate gateway aggregation and verify strict namespacing rules
    merged_schemas: dict[str, tuple[str, str]] = {}
    errors: list[str] = []

    for service_name, spec in raw_schemas.items():
        prefix = SERVICES_CONFIG[service_name]["prefix"]
        schemas = spec.get("components", {}).get("schemas", {})

        for schema_name in schemas:
            # Check if name is correctly prefixed
            namespaced_name = f"{prefix}{schema_name}"

            # Guardrail: The prefix must be non-empty and namespaced_name must start with the prefix
            if not prefix or not namespaced_name.startswith(prefix):
                errors.append(
                    f"Service '{service_name}' model '{schema_name}' is not correctly namespaced. "
                    f"Expected prefix '{prefix}'."
                )
                continue

            # Detect naming collisions on the aggregated components map
            if namespaced_name in merged_schemas:
                other_service, other_orig = merged_schemas[namespaced_name]
                errors.append(
                    f"Namespace collision detected! Both service '{service_name}' (schema '{schema_name}') "
                    f"and service '{other_service}' (schema '{other_orig}') mapped to identical "
                    f"aggregated schema key '{namespaced_name}'."
                )
            else:
                merged_schemas[namespaced_name] = (service_name, schema_name)

    if errors:
        print(
            "\n[VALIDATION FAILED] Namespacing and collision checks failed:",
            file=sys.stderr,
        )
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        print(
            "\nTroubleshooting Reference: Please refer to CONTRIBUTING.md#schema-validation-failures "
            "for instructions on how to resolve namespace collisions or prefix issues.",
            file=sys.stderr,
        )
        return False

    print(
        "\n[VALIDATION PASSED] All schemas are isolated, correctly namespaced, and free of collisions."
    )
    return True


if __name__ == "__main__":
    import json

    export_dir = None
    if "--export-dir" in sys.argv:
        idx = sys.argv.index("--export-dir")
        if idx + 1 < len(sys.argv):
            export_dir = sys.argv[idx + 1]

    success = validate_schemas()
    if not success:
        sys.exit(1)

    if export_dir:
        os.makedirs(export_dir, exist_ok=True)
        print(f"\n[EXPORT] Exporting OpenAPI schemas to '{export_dir}'...")
        for name, config in SERVICES_CONFIG.items():
            app = config["app"]
            schema = app.openapi()
            out_file = os.path.join(export_dir, f"{name}_openapi.json")
            with open(out_file, "w") as f:
                json.dump(schema, f, indent=2)
                f.write("\n")
            print(f"  - Exported {out_file}")

        # Also export the gateway app's openapi schema as cdisc_openapi.json
        try:
            from apps.gateway.main import app as gateway_app

            gateway_schema = gateway_app.openapi()
            gateway_out_file = os.path.join(export_dir, "cdisc_openapi.json")
            with open(gateway_out_file, "w") as f:
                json.dump(gateway_schema, f, indent=2)
                f.write("\n")
            print(f"  - Exported {gateway_out_file}")
        except Exception as e:
            print(
                f"Warning: Failed to export gateway schema (cdisc_openapi.json): {e}",
                file=sys.stderr,
            )

    sys.exit(0)
