import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import {
  validateGatewayRequest,
  generateGatewaySignature,
  isWhitelistedSubjectRoute,
  isPathSignatureGated,
  GATEWAY_SECRET,
} from "../mockGateway.js";

describe("Mock Gateway Simulator Unit Tests", () => {
  let consoleSpy;

  beforeEach(() => {
    consoleSpy = vi.spyOn(console, "error").mockImplementation(() => {});
  });

  afterEach(() => {
    consoleSpy.mockRestore();
  });

  describe("Path Prefix Validation and Stripping", () => {
    it("should accept valid service path prefixes and strip them", async () => {
      const req = new Request("http://localhost:8000/designer/studies/STUDY-01", {
        method: "GET",
      });
      const result = await validateGatewayRequest(req);
      expect(result.valid).toBe(true);
      expect(result.strippedPath).toBe("studies/STUDY-01");
    });

    it("should reject invalid path prefixes and log console error", async () => {
      const req = new Request("http://localhost:8000/invalid-service/endpoint", {
        method: "GET",
      });
      const result = await validateGatewayRequest(req);
      expect(result.valid).toBe(false);
      expect(result.status).toBe(400);
      expect(result.body.error).toBe("INVALID_PATH_PREFIX");
      expect(consoleSpy).toHaveBeenCalledWith(
        expect.stringContaining("Invalid path prefix intercepted")
      );
    });
  });

  describe("Subject Role Administrative Access Enforcement", () => {
    it("should allow whitelisted Subject routes for Subject principal", async () => {
      const req = new Request(
        "http://localhost:8000/api/v1/interop/assignments/subject/sub-001",
        {
          method: "GET",
          headers: {
            "X-User-Roles": "Subject",
            "X-User-Id": "sub-001",
          },
        }
      );
      const result = await validateGatewayRequest(req);
      expect(result.valid).toBe(true);
    });

    it("should block unwhitelisted administrative routes for Subject principal with 403 Forbidden", async () => {
      const req = new Request("http://localhost:8000/api/v1/studies", {
        method: "GET",
        headers: {
          "X-User-Roles": "Subject",
          "X-User-Id": "sub-001",
        },
      });
      const result = await validateGatewayRequest(req);
      expect(result.valid).toBe(false);
      expect(result.status).toBe(403);
      expect(result.body.detail).toContain("Access denied: Subject principal is not authorized");
      expect(consoleSpy).toHaveBeenCalledWith(
        expect.stringContaining("403 Forbidden: Subject role attempted to access administrative route")
      );
    });

    it("should block administrative eCRF mutation attempts from Subject principal", async () => {
      const req = new Request("http://localhost:8000/api/v1/execution/subjects", {
        method: "POST",
        headers: {
          "X-User-Roles": "subject",
          "X-User-Id": "sub-001",
        },
      });
      const result = await validateGatewayRequest(req);
      expect(result.valid).toBe(false);
      expect(result.status).toBe(403);
    });
  });

  describe("Dual-Signature Header Validation", () => {
    it("should reject signature-gated mutations missing X-Sig-Token and log console error", async () => {
      const req = new Request("http://localhost:8000/api/v1/execution/queries/sync", {
        method: "POST",
        headers: {
          "X-User-Roles": "Data Manager",
          "X-User-Id": "user-001",
        },
      });
      const result = await validateGatewayRequest(req);
      expect(result.valid).toBe(false);
      expect(result.status).toBe(401);
      expect(result.body.detail).toBe("REAUTHENTICATION_REQUIRED");
      expect(consoleSpy).toHaveBeenCalledWith(
        expect.stringContaining("Missing or invalid e-signature header (X-Sig-Token)")
      );
    });

    it("should accept signature-gated mutations when valid X-Sig-Token is supplied", async () => {
      const req = new Request("http://localhost:8000/api/v1/execution/queries/sync", {
        method: "POST",
        headers: {
          "X-User-Roles": "Data Manager",
          "X-User-Id": "user-001",
          "X-Sig-Token": "valid-reauth-sig-token-jwt",
        },
      });
      const result = await validateGatewayRequest(req);
      expect(result.valid).toBe(true);
    });

    it("should verify valid X-Gateway-Signature HMAC-SHA256 headers generated by browser Crypto API", async () => {
      const userId = "usr-123";
      const roles = "Sponsor Admin";
      const timestamp = "1700000000";
      const changeReason = "Initial baseline release";

      const validSig = await generateGatewaySignature(
        userId,
        roles,
        timestamp,
        "2",
        changeReason,
        GATEWAY_SECRET
      );

      const req = new Request("http://localhost:8000/designer/studies", {
        method: "GET",
        headers: {
          "X-User-Id": userId,
          "X-User-Roles": roles,
          "X-Gateway-Timestamp": timestamp,
          "X-Gateway-Signature": validSig,
          "X-Signature-Version": "2",
          "X-Change-Reason": changeReason,
        },
      });

      const result = await validateGatewayRequest(req);
      expect(result.valid).toBe(true);
    });

    it("should reject invalid/tampered X-Gateway-Signature and log console error", async () => {
      const req = new Request("http://localhost:8000/designer/studies", {
        method: "GET",
        headers: {
          "X-User-Id": "usr-123",
          "X-User-Roles": "Sponsor Admin",
          "X-Gateway-Timestamp": "1700000000",
          "X-Gateway-Signature": "deadbeef1234567890badc0de", // pragma: allowlist secret
          "X-Signature-Version": "2",
        },
      });

      const result = await validateGatewayRequest(req);
      expect(result.valid).toBe(false);
      expect(result.status).toBe(401);
      expect(result.body.detail).toBe("Invalid gateway signature");
      expect(consoleSpy).toHaveBeenCalledWith(
        expect.stringContaining("Invalid or tampered X-Gateway-Signature header")
      );
    });
  });

  describe("Helper Functions", () => {
    it("should identify signature-gated paths correctly", () => {
      expect(isPathSignatureGated("execution/sign")).toBe(true);
      expect(isPathSignatureGated("execution/approve")).toBe(true);
      expect(isPathSignatureGated("execution/unblind")).toBe(true);
      expect(isPathSignatureGated("execution/read")).toBe(false);
      expect(isPathSignatureGated("")).toBe(false);
    });

    it("should check subject route whitelisting correctly", () => {
      expect(isWhitelistedSubjectRoute("health", "GET")).toBe(true);
      expect(isWhitelistedSubjectRoute("me", "GET")).toBe(true);
      expect(isWhitelistedSubjectRoute("designer/studies", "GET")).toBe(false);
      expect(isWhitelistedSubjectRoute("", "GET")).toBe(false);
    });
  });
});
