"""Initial baseline

Revision ID: f7ebdb42c09c
Revises: None
Create Date: 2026-08-04 13:04:56.667148

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7ebdb42c09c"  # pragma: allowlist secret
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tmf_audit_ledger_seals",
        sa.Column("block_index", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("previous_block_hash", sa.String(length=64), nullable=False),
        sa.Column("current_block_hash", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("sealed_record_count", sa.Integer(), nullable=False),
        sa.Column("merkle_root_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("block_index"),
    )
    op.create_table(
        "tmf_audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("user_role", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("details", sa.String(length=1000), nullable=False),
        sa.Column("cryptographic_seal", sa.String(length=64), nullable=True),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tmf_audit_logs_document_id"),
        "tmf_audit_logs",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_audit_logs_timestamp"),
        "tmf_audit_logs",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_audit_logs_user_id"), "tmf_audit_logs", ["user_id"], unique=False
    )
    op.create_table(
        "tmf_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=255), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("site_id", sa.String(length=255), nullable=True),
        sa.Column("zone", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=255), nullable=False),
        sa.Column("artifact_type", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("taxonomy_version", sa.String(length=50), nullable=False),
        sa.Column("artifact_code", sa.String(length=50), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("expiration_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("document_owner_id", sa.String(length=255), nullable=True),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=True),
        sa.Column("protocol_version_tag", sa.String(length=50), nullable=True),
        sa.Column("protocol_version_index", sa.Integer(), nullable=True),
        sa.Column("protocol_version_status", sa.String(length=50), nullable=True),
        sa.Column("document_type", sa.String(length=50), nullable=True),
        sa.Column("approval_status", sa.String(length=50), nullable=False),
        sa.Column("signature_manifestation", sa.JSON(), nullable=True),
        sa.Column("signer", sa.String(length=255), nullable=True),
        sa.Column("signing_timestamp", sa.DateTime(), nullable=True),
        sa.Column("is_redacted", sa.Boolean(), nullable=False),
        sa.Column("redaction_source_id", sa.String(length=36), nullable=True),
        sa.Column("redaction_manifest_json", sa.JSON(), nullable=True),
        sa.Column("correlation_key", sa.String(length=255), nullable=True),
        sa.Column("content_checksum", sa.String(length=64), nullable=True),
        sa.Column("source_system", sa.String(length=255), nullable=True),
        sa.Column("sync_status", sa.String(length=50), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'TECHNICAL_QC', 'CLINICAL_QC', 'APPROVED', 'ARCHIVED', 'REJECTED', 'SIGNED')",
            name="chk_tmf_document_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tmf_documents_artifact_code"),
        "tmf_documents",
        ["artifact_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_documents_artifact_type"),
        "tmf_documents",
        ["artifact_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_documents_correlation_key"),
        "tmf_documents",
        ["correlation_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_documents_document_owner_id"),
        "tmf_documents",
        ["document_owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_documents_document_type"),
        "tmf_documents",
        ["document_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_documents_expiration_date"),
        "tmf_documents",
        ["expiration_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_documents_idempotency_key"),
        "tmf_documents",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_documents_issue_date"),
        "tmf_documents",
        ["issue_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_documents_redaction_source_id"),
        "tmf_documents",
        ["redaction_source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_documents_site_id"), "tmf_documents", ["site_id"], unique=False
    )
    op.create_index(
        op.f("ix_tmf_documents_study_id"), "tmf_documents", ["study_id"], unique=False
    )
    op.create_index(
        op.f("ix_tmf_documents_zone"), "tmf_documents", ["zone"], unique=False
    )
    op.create_table(
        "tmf_expected_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=255), nullable=False),
        sa.Column("site_id", sa.String(length=255), nullable=True),
        sa.Column("milestone", sa.String(length=255), nullable=False),
        sa.Column("artifact_type", sa.String(length=255), nullable=False),
        sa.Column("zone", sa.Integer(), nullable=True),
        sa.Column("section", sa.String(length=255), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tmf_expected_documents_artifact_type"),
        "tmf_expected_documents",
        ["artifact_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_expected_documents_milestone"),
        "tmf_expected_documents",
        ["milestone"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_expected_documents_site_id"),
        "tmf_expected_documents",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_expected_documents_study_id"),
        "tmf_expected_documents",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "tmf_document_expiration_alert_states",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("warning_window", sa.String(length=50), nullable=False),
        sa.Column("alerted_at", sa.DateTime(), nullable=False),
        sa.Column("dispatched", sa.Boolean(), nullable=False),
        sa.Column("notification_id", sa.String(length=255), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"], ["tmf_documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id", "warning_window", name="uq_tmf_doc_expiration_alert_state"
        ),
    )
    op.create_index(
        op.f("ix_tmf_document_expiration_alert_states_dispatched"),
        "tmf_document_expiration_alert_states",
        ["dispatched"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_document_expiration_alert_states_document_id"),
        "tmf_document_expiration_alert_states",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_document_expiration_alert_states_notification_id"),
        "tmf_document_expiration_alert_states",
        ["notification_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_document_expiration_alert_states_warning_window"),
        "tmf_document_expiration_alert_states",
        ["warning_window"],
        unique=False,
    )
    op.create_table(
        "tmf_document_qc_transitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("transition_sequence", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=50), nullable=False),
        sa.Column("to_status", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("actor_role", sa.String(length=255), nullable=False),
        sa.Column("reason_for_change", sa.String(length=1000), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"], ["tmf_documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id", "transition_sequence", name="uq_document_transition_sequence"
        ),
    )
    op.create_index(
        "ix_tmf_document_qc_transitions_doc_seq",
        "tmf_document_qc_transitions",
        ["document_id", "transition_sequence"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_document_qc_transitions_document_id"),
        "tmf_document_qc_transitions",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tmf_document_qc_transitions_timestamp"),
        "tmf_document_qc_transitions",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tmf_document_qc_transitions_timestamp"),
        table_name="tmf_document_qc_transitions",
    )
    op.drop_index(
        op.f("ix_tmf_document_qc_transitions_document_id"),
        table_name="tmf_document_qc_transitions",
    )
    op.drop_index(
        "ix_tmf_document_qc_transitions_doc_seq",
        table_name="tmf_document_qc_transitions",
    )
    op.drop_table("tmf_document_qc_transitions")
    op.drop_index(
        op.f("ix_tmf_document_expiration_alert_states_warning_window"),
        table_name="tmf_document_expiration_alert_states",
    )
    op.drop_index(
        op.f("ix_tmf_document_expiration_alert_states_notification_id"),
        table_name="tmf_document_expiration_alert_states",
    )
    op.drop_index(
        op.f("ix_tmf_document_expiration_alert_states_document_id"),
        table_name="tmf_document_expiration_alert_states",
    )
    op.drop_index(
        op.f("ix_tmf_document_expiration_alert_states_dispatched"),
        table_name="tmf_document_expiration_alert_states",
    )
    op.drop_table("tmf_document_expiration_alert_states")
    op.drop_index(
        op.f("ix_tmf_expected_documents_study_id"), table_name="tmf_expected_documents"
    )
    op.drop_index(
        op.f("ix_tmf_expected_documents_site_id"), table_name="tmf_expected_documents"
    )
    op.drop_index(
        op.f("ix_tmf_expected_documents_milestone"), table_name="tmf_expected_documents"
    )
    op.drop_index(
        op.f("ix_tmf_expected_documents_artifact_type"),
        table_name="tmf_expected_documents",
    )
    op.drop_table("tmf_expected_documents")
    op.drop_index(op.f("ix_tmf_documents_zone"), table_name="tmf_documents")
    op.drop_index(op.f("ix_tmf_documents_study_id"), table_name="tmf_documents")
    op.drop_index(op.f("ix_tmf_documents_site_id"), table_name="tmf_documents")
    op.drop_index(
        op.f("ix_tmf_documents_redaction_source_id"), table_name="tmf_documents"
    )
    op.drop_index(op.f("ix_tmf_documents_issue_date"), table_name="tmf_documents")
    op.drop_index(op.f("ix_tmf_documents_idempotency_key"), table_name="tmf_documents")
    op.drop_index(op.f("ix_tmf_documents_expiration_date"), table_name="tmf_documents")
    op.drop_index(op.f("ix_tmf_documents_document_type"), table_name="tmf_documents")
    op.drop_index(
        op.f("ix_tmf_documents_document_owner_id"), table_name="tmf_documents"
    )
    op.drop_index(op.f("ix_tmf_documents_correlation_key"), table_name="tmf_documents")
    op.drop_index(op.f("ix_tmf_documents_artifact_type"), table_name="tmf_documents")
    op.drop_index(op.f("ix_tmf_documents_artifact_code"), table_name="tmf_documents")
    op.drop_table("tmf_documents")
    op.drop_index(op.f("ix_tmf_audit_logs_user_id"), table_name="tmf_audit_logs")
    op.drop_index(op.f("ix_tmf_audit_logs_timestamp"), table_name="tmf_audit_logs")
    op.drop_index(op.f("ix_tmf_audit_logs_document_id"), table_name="tmf_audit_logs")
    op.drop_table("tmf_audit_logs")
    op.drop_table("tmf_audit_ledger_seals")
    # ### end Alembic commands ###
